// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: aliyun_openapi_meta.proto

package pbmeta

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandDefinition is the stable, API-agnostic metadata schema interpreted by
// common-runtime. It describes an operation; it does not generate one Go type
// per Alibaba Cloud API.
type CommandDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductCode   string                 `protobuf:"bytes,1,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CmdName       string                 `protobuf:"bytes,3,opt,name=cmd_name,json=cmdName,proto3" json:"cmd_name,omitempty"`
	CmdFullName   string                 `protobuf:"bytes,4,opt,name=cmd_full_name,json=cmdFullName,proto3" json:"cmd_full_name,omitempty"`
	DescriptionZh string                 `protobuf:"bytes,5,opt,name=description_zh,json=descriptionZh,proto3" json:"description_zh,omitempty"`
	DescriptionEn string                 `protobuf:"bytes,6,opt,name=description_en,json=descriptionEn,proto3" json:"description_en,omitempty"`
	Method        string                 `protobuf:"bytes,7,opt,name=method,proto3" json:"method,omitempty"`
	MultiVersion  bool                   `protobuf:"varint,8,opt,name=multi_version,json=multiVersion,proto3" json:"multi_version,omitempty"`
	Deprecated    bool                   `protobuf:"varint,9,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	KebabExample  string                 `protobuf:"bytes,10,opt,name=kebab_example,json=kebabExample,proto3" json:"kebab_example,omitempty"`
	CamelExample  string                 `protobuf:"bytes,11,opt,name=camel_example,json=camelExample,proto3" json:"camel_example,omitempty"`
	Operation     *Operation             `protobuf:"bytes,12,opt,name=operation,proto3" json:"operation,omitempty"`
	Parameters    []*Argument            `protobuf:"bytes,13,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandDefinition) Reset() {
	*x = CommandDefinition{}
	mi := &file_aliyun_openapi_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDefinition) ProtoMessage() {}

func (x *CommandDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_aliyun_openapi_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDefinition.ProtoReflect.Descriptor instead.
func (*CommandDefinition) Descriptor() ([]byte, []int) {
	return file_aliyun_openapi_meta_proto_rawDescGZIP(), []int{0}
}

func (x *CommandDefinition) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *CommandDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandDefinition) GetCmdName() string {
	if x != nil {
		return x.CmdName
	}
	return ""
}

func (x *CommandDefinition) GetCmdFullName() string {
	if x != nil {
		return x.CmdFullName
	}
	return ""
}

func (x *CommandDefinition) GetDescriptionZh() string {
	if x != nil {
		return x.DescriptionZh
	}
	return ""
}

func (x *CommandDefinition) GetDescriptionEn() string {
	if x != nil {
		return x.DescriptionEn
	}
	return ""
}

func (x *CommandDefinition) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CommandDefinition) GetMultiVersion() bool {
	if x != nil {
		return x.MultiVersion
	}
	return false
}

func (x *CommandDefinition) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *CommandDefinition) GetKebabExample() string {
	if x != nil {
		return x.KebabExample
	}
	return ""
}

func (x *CommandDefinition) GetCamelExample() string {
	if x != nil {
		return x.CamelExample
	}
	return ""
}

func (x *CommandDefinition) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *CommandDefinition) GetParameters() []*Argument {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	ApiStyle      string                 `protobuf:"bytes,2,opt,name=api_style,json=apiStyle,proto3" json:"api_style,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,3,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Protocol      string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_aliyun_openapi_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_aliyun_openapi_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_aliyun_openapi_meta_proto_rawDescGZIP(), []int{1}
}

func (x *Operation) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Operation) GetApiStyle() string {
	if x != nil {
		return x.ApiStyle
	}
	return ""
}

func (x *Operation) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Operation) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Operation) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Operation) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Argument struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RawName  string                 `protobuf:"bytes,2,opt,name=raw_name,json=rawName,proto3" json:"raw_name,omitempty"`
	Type     string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Options  []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	HelpZh   string                 `protobuf:"bytes,5,opt,name=help_zh,json=helpZh,proto3" json:"help_zh,omitempty"`
	HelpEn   string                 `protobuf:"bytes,6,opt,name=help_en,json=helpEn,proto3" json:"help_en,omitempty"`
	Required bool                   `protobuf:"varint,7,opt,name=required,proto3" json:"required,omitempty"`
	// default_json preserves JSON scalar/object/array precision and shape. The
	// separate presence bit distinguishes an absent default from JSON null.
	DefaultJson   []byte      `protobuf:"bytes,8,opt,name=default_json,json=defaultJson,proto3" json:"default_json,omitempty"`
	HasDefault    bool        `protobuf:"varint,9,opt,name=has_default,json=hasDefault,proto3" json:"has_default,omitempty"`
	Location      string      `protobuf:"bytes,10,opt,name=location,proto3" json:"location,omitempty"`
	ParamStyle    string      `protobuf:"bytes,11,opt,name=param_style,json=paramStyle,proto3" json:"param_style,omitempty"`
	ElementType   string      `protobuf:"bytes,12,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"`
	ValueType     string      `protobuf:"bytes,13,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	Fields        []*Argument `protobuf:"bytes,14,rep,name=fields,proto3" json:"fields,omitempty"`
	ElementFields []*Argument `protobuf:"bytes,15,rep,name=element_fields,json=elementFields,proto3" json:"element_fields,omitempty"`
	ValueFields   []*Argument `protobuf:"bytes,16,rep,name=value_fields,json=valueFields,proto3" json:"value_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Argument) Reset() {
	*x = Argument{}
	mi := &file_aliyun_openapi_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Argument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Argument) ProtoMessage() {}

func (x *Argument) ProtoReflect() protoreflect.Message {
	mi := &file_aliyun_openapi_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Argument.ProtoReflect.Descriptor instead.
func (*Argument) Descriptor() ([]byte, []int) {
	return file_aliyun_openapi_meta_proto_rawDescGZIP(), []int{2}
}

func (x *Argument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Argument) GetRawName() string {
	if x != nil {
		return x.RawName
	}
	return ""
}

func (x *Argument) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Argument) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Argument) GetHelpZh() string {
	if x != nil {
		return x.HelpZh
	}
	return ""
}

func (x *Argument) GetHelpEn() string {
	if x != nil {
		return x.HelpEn
	}
	return ""
}

func (x *Argument) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Argument) GetDefaultJson() []byte {
	if x != nil {
		return x.DefaultJson
	}
	return nil
}

func (x *Argument) GetHasDefault() bool {
	if x != nil {
		return x.HasDefault
	}
	return false
}

func (x *Argument) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Argument) GetParamStyle() string {
	if x != nil {
		return x.ParamStyle
	}
	return ""
}

func (x *Argument) GetElementType() string {
	if x != nil {
		return x.ElementType
	}
	return ""
}

func (x *Argument) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

func (x *Argument) GetFields() []*Argument {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Argument) GetElementFields() []*Argument {
	if x != nil {
		return x.ElementFields
	}
	return nil
}

func (x *Argument) GetValueFields() []*Argument {
	if x != nil {
		return x.ValueFields
	}
	return nil
}

var File_aliyun_openapi_meta_proto protoreflect.FileDescriptor

const file_aliyun_openapi_meta_proto_rawDesc = "" +
	"\n" +
	"\x19aliyun_openapi_meta.proto\x12\x16aliyun.openapi.meta.v1\"\x81\x04\n" +
	"\x11CommandDefinition\x12!\n" +
	"\fproduct_code\x18\x01 \x01(\tR\vproductCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bcmd_name\x18\x03 \x01(\tR\acmdName\x12\"\n" +
	"\rcmd_full_name\x18\x04 \x01(\tR\vcmdFullName\x12%\n" +
	"\x0edescription_zh\x18\x05 \x01(\tR\rdescriptionZh\x12%\n" +
	"\x0edescription_en\x18\x06 \x01(\tR\rdescriptionEn\x12\x16\n" +
	"\x06method\x18\a \x01(\tR\x06method\x12#\n" +
	"\rmulti_version\x18\b \x01(\bR\fmultiVersion\x12\x1e\n" +
	"\n" +
	"deprecated\x18\t \x01(\bR\n" +
	"deprecated\x12#\n" +
	"\rkebab_example\x18\n" +
	" \x01(\tR\fkebabExample\x12#\n" +
	"\rcamel_example\x18\v \x01(\tR\fcamelExample\x12?\n" +
	"\toperation\x18\f \x01(\v2!.aliyun.openapi.meta.v1.OperationR\toperation\x12@\n" +
	"\n" +
	"parameters\x18\r \x03(\v2 .aliyun.openapi.meta.v1.ArgumentR\n" +
	"parameters\"\xa7\x01\n" +
	"\tOperation\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1b\n" +
	"\tapi_style\x18\x02 \x01(\tR\bapiStyle\x12\x1f\n" +
	"\vapi_version\x18\x03 \x01(\tR\n" +
	"apiVersion\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\"\xc0\x04\n" +
	"\bArgument\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\braw_name\x18\x02 \x01(\tR\arawName\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\x12\x17\n" +
	"\ahelp_zh\x18\x05 \x01(\tR\x06helpZh\x12\x17\n" +
	"\ahelp_en\x18\x06 \x01(\tR\x06helpEn\x12\x1a\n" +
	"\brequired\x18\a \x01(\bR\brequired\x12!\n" +
	"\fdefault_json\x18\b \x01(\fR\vdefaultJson\x12\x1f\n" +
	"\vhas_default\x18\t \x01(\bR\n" +
	"hasDefault\x12\x1a\n" +
	"\blocation\x18\n" +
	" \x01(\tR\blocation\x12\x1f\n" +
	"\vparam_style\x18\v \x01(\tR\n" +
	"paramStyle\x12!\n" +
	"\felement_type\x18\f \x01(\tR\velementType\x12\x1d\n" +
	"\n" +
	"value_type\x18\r \x01(\tR\tvalueType\x128\n" +
	"\x06fields\x18\x0e \x03(\v2 .aliyun.openapi.meta.v1.ArgumentR\x06fields\x12G\n" +
	"\x0eelement_fields\x18\x0f \x03(\v2 .aliyun.openapi.meta.v1.ArgumentR\relementFields\x12C\n" +
	"\fvalue_fields\x18\x10 \x03(\v2 .aliyun.openapi.meta.v1.ArgumentR\vvalueFieldsB8Z6github.com/aliyun/aliyun-openapi-runtime/pbmeta;pbmetab\x06proto3"

var (
	file_aliyun_openapi_meta_proto_rawDescOnce sync.Once
	file_aliyun_openapi_meta_proto_rawDescData []byte
)

func file_aliyun_openapi_meta_proto_rawDescGZIP() []byte {
	file_aliyun_openapi_meta_proto_rawDescOnce.Do(func() {
		file_aliyun_openapi_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aliyun_openapi_meta_proto_rawDesc), len(file_aliyun_openapi_meta_proto_rawDesc)))
	})
	return file_aliyun_openapi_meta_proto_rawDescData
}

var file_aliyun_openapi_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_aliyun_openapi_meta_proto_goTypes = []any{
	(*CommandDefinition)(nil), // 0: aliyun.openapi.meta.v1.CommandDefinition
	(*Operation)(nil),         // 1: aliyun.openapi.meta.v1.Operation
	(*Argument)(nil),          // 2: aliyun.openapi.meta.v1.Argument
}
var file_aliyun_openapi_meta_proto_depIdxs = []int32{
	1, // 0: aliyun.openapi.meta.v1.CommandDefinition.operation:type_name -> aliyun.openapi.meta.v1.Operation
	2, // 1: aliyun.openapi.meta.v1.CommandDefinition.parameters:type_name -> aliyun.openapi.meta.v1.Argument
	2, // 2: aliyun.openapi.meta.v1.Argument.fields:type_name -> aliyun.openapi.meta.v1.Argument
	2, // 3: aliyun.openapi.meta.v1.Argument.element_fields:type_name -> aliyun.openapi.meta.v1.Argument
	2, // 4: aliyun.openapi.meta.v1.Argument.value_fields:type_name -> aliyun.openapi.meta.v1.Argument
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_aliyun_openapi_meta_proto_init() }
func file_aliyun_openapi_meta_proto_init() {
	if File_aliyun_openapi_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aliyun_openapi_meta_proto_rawDesc), len(file_aliyun_openapi_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aliyun_openapi_meta_proto_goTypes,
		DependencyIndexes: file_aliyun_openapi_meta_proto_depIdxs,
		MessageInfos:      file_aliyun_openapi_meta_proto_msgTypes,
	}.Build()
	File_aliyun_openapi_meta_proto = out.File
	file_aliyun_openapi_meta_proto_goTypes = nil
	file_aliyun_openapi_meta_proto_depIdxs = nil
}
