/*
 * Copyright (C) 2017-2018 Alibaba Group Holding Limited
 */
package meta

var profileJson = []byte(`
{
  "products": [{
    "name": "Vpc",
    "major_version": "2016-04-28",
    "domain": "vpc.aliyuncs.com,vpc.[RegionId].aliyuncs.com,vpc-openapi-share.[RegionId].aliyuncs.com,vpc-openapi-share.aliyuncs.com",
    "location_service_code": "vpc",
    "endpoints": {
      "ap-northeast-1": "vpc.ap-northeast-1.aliyuncs.com",
      "ap-southeast-1": "vpc.aliyuncs.com",
      "ap-southeast-2": "vpc.ap-southeast-2.aliyuncs.com",
      "cn-anhui-gov": "vpc.aliyuncs.com",
      "cn-beijing": "vpc.aliyuncs.com",
      "cn-beijing-am13-c01": "vpc.aliyuncs.com",
      "cn-gansu-am6": "vpc.aliyuncs.com",
      "cn-guizhou": "vpc.aliyuncs.com",
      "cn-guizhou-gov": "vpc.aliyuncs.com",
      "cn-haidian-cm12-c01": "vpc.aliyuncs.com",
      "cn-hangzhou": "vpc.aliyuncs.com",
      "cn-henan-am12001": "vpc.aliyuncs.com",
      "cn-hongkong": "vpc.aliyuncs.com",
      "cn-ningxia-am7-c01": "vpc.aliyuncs.com",
      "cn-ningxiazhongwei": "vpc.aliyuncs.com",
      "cn-shanghai": "vpc.aliyuncs.com",
      "cn-shanghai-finance-1": "vpc.aliyuncs.com",
      "cn-shenzhen": "vpc.aliyuncs.com",
      "cn-shenzhen-finance-1": "vpc.aliyuncs.com",
      "cn-zhangjiakou": "vpc.cn-zhangjiakou.aliyuncs.com",
      "eu-central-1": "vpc.eu-central-1.aliyuncs.com",
      "me-east-1": "vpc.me-east-1.aliyuncs.com",
      "us-east-1": "vpc.aliyuncs.com",
      "us-west-1": "vpc.aliyuncs.com"
    }
  }, {
    "name": "Buss",
    "major_version": "2016-07-18",
    "domain": "buss.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Intlsupport-inner",
    "major_version": "2016-12-08",
    "domain": "intlsupport-cn-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Iot",
    "major_version": "2016-05-30",
    "domain": "iot.aliyuncs.com,iot.[RegionId].aliyuncs.com,iot-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "iot.ap-southeast-1.aliyuncs.com",
      "cn-beijing": "iot.aliyuncs.com",
      "cn-beijing-inner": "iot.aliyuncs.com",
      "cn-hangzhou": "iot.aliyuncs.com",
      "cn-hangzhou-d": "iot.aliyuncs.com",
      "cn-hongkong": "iot.aliyuncs.com",
      "cn-qingdao": "iot.aliyuncs.com",
      "cn-qingdao-cm9": "iot.aliyuncs.com",
      "cn-shanghai": "iot.cn-shanghai.aliyuncs.com",
      "cn-shanghai-et2-b01": "iot.aliyuncs.com",
      "cn-shanghai-inner": "iot.aliyuncs.com",
      "cn-shenzhen": "iot.aliyuncs.com",
      "cn-shenzhen-inner": "iot.aliyuncs.com",
      "us-east-1": "iot.aliyuncs.com",
      "us-west-1": "iot.us-west-1.aliyuncs.com"
    }
  }, {
    "name": "SSP",
    "major_version": "2017-09-26",
    "domain": "ssp.aliyuncs.com,ssp.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "yundun-gray-control",
    "major_version": "2017-08-16",
    "domain": "yundun-gray-control-share.aliyuncs.com,yundun-gray-control.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "CloudDesktop",
    "major_version": "2017-03-01",
    "domain": "clouddesktop.[RegionId].aliyuncs.com",
    "location_service_code": "clouddesktop",
    "endpoints": {}
  }, {
    "name": "Dts",
    "major_version": "2016-08-01",
    "domain": "dts.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "dts.aliyuncs.com",
      "cn-beijing": "dts.aliyuncs.com",
      "cn-beijing-inner": "dts.aliyuncs.com",
      "cn-hangzhou": "dts.aliyuncs.com",
      "cn-hangzhou-d": "dts.aliyuncs.com",
      "cn-hongkong": "dts.aliyuncs.com",
      "cn-qingdao": "dts.aliyuncs.com",
      "cn-qingdao-cm9": "dts.aliyuncs.com",
      "cn-shanghai": "dts.aliyuncs.com",
      "cn-shanghai-et2-b01": "dts.aliyuncs.com",
      "cn-shanghai-inner": "dts.aliyuncs.com",
      "cn-shenzhen": "dts.aliyuncs.com",
      "cn-shenzhen-inner": "dts.aliyuncs.com",
      "us-east-1": "dts.aliyuncs.com",
      "us-west-1": "dts.aliyuncs.com"
    }
  }, {
    "name": "Httpdns",
    "major_version": "2016-02-01",
    "domain": "httpdns-api.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "httpdns-api.aliyuncs.com",
      "cn-beijing": "httpdns-api.aliyuncs.com",
      "cn-beijing-inner": "httpdns-api.aliyuncs.com",
      "cn-hangzhou": "httpdns-api.aliyuncs.com",
      "cn-hangzhou-d": "httpdns-api.aliyuncs.com",
      "cn-hongkong": "httpdns-api.aliyuncs.com",
      "cn-qingdao": "httpdns-api.aliyuncs.com",
      "cn-qingdao-cm9": "httpdns-api.aliyuncs.com",
      "cn-shanghai": "httpdns-api.aliyuncs.com",
      "cn-shanghai-et2-b01": "httpdns-api.aliyuncs.com",
      "cn-shanghai-inner": "httpdns-api.aliyuncs.com",
      "cn-shenzhen": "httpdns-api.aliyuncs.com",
      "cn-shenzhen-inner": "httpdns-api.aliyuncs.com",
      "us-east-1": "httpdns-api.aliyuncs.com",
      "us-west-1": "httpdns-api.aliyuncs.com"
    }
  }, {
    "name": "LangYan",
    "major_version": "2016-08-23",
    "domain": "langyan-inner.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Ubsms",
    "major_version": "2015-06-23",
    "domain": "ubsms.aliyuncs.com,ubsms.[RegionId].aliyuncs.com,ubsms-center.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "ubsms.aliyuncs.com",
      "cn-beijing": "ubsms.aliyuncs.com",
      "cn-beijing-inner": "ubsms.aliyuncs.com",
      "cn-hangzhou": "ubsms.aliyuncs.com",
      "cn-hangzhou-d": "ubsms.aliyuncs.com",
      "cn-hongkong": "ubsms.aliyuncs.com",
      "cn-qingdao": "ubsms.cn-qingdao.aliyuncs.com",
      "cn-qingdao-cm9": "ubsms.aliyuncs.com",
      "cn-shanghai": "ubsms.aliyuncs.com",
      "cn-shanghai-et2-b01": "ubsms.aliyuncs.com",
      "cn-shanghai-inner": "ubsms.aliyuncs.com",
      "cn-shenzhen": "ubsms.aliyuncs.com",
      "cn-shenzhen-inner": "ubsms.aliyuncs.com",
      "us-east-1": "ubsms.aliyuncs.com",
      "us-west-1": "ubsms.aliyuncs.com"
    }
  }, {
    "name": "ARMS",
    "major_version": "2016-11-25",
    "domain": "arms.aliyuncs.com,arms.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "cn-beijing": "arms.cn-beijing.aliyuncs.com",
      "cn-hangzhou": "arms.cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "arms.cn-shanghai.aliyuncs.com",
      "cn-shenzhen": "arms.cn-shenzhen.aliyuncs.com"
    }
  }, {
    "name": "Alidns-inner",
    "major_version": "2016-12-01",
    "domain": "alidns-inner.aliyuncs.com,alidns-inner-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "EHPC",
    "major_version": "2017-07-14",
    "domain": "ehpc.aliyuncs.com,ehpc.[RegionId].aliyuncs.com",
    "location_service_code": "ehs",
    "endpoints": {}
  }, {
    "name": "alimail-inner",
    "major_version": "2017-03-01",
    "domain": "alimail-inner.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "ddosbgp-inc",
    "major_version": "2017-11-16",
    "domain": "ddosbgp-inc-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Ess-inner",
    "major_version": "2017-01-25",
    "domain": "ess-inner.aliyuncs.com,ess-inner.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "IDST",
    "major_version": "2017-09-22",
    "domain": "idst.[RegionId].aliyuncs.com",
    "location_service_code": "imagesearch",
    "endpoints": {}
  }, {
    "name": "Risk",
    "major_version": "2016-07-13",
    "domain": "risk-cn-hangzhou.aliyuncs.com,riskcontrol-inner.aliyuncs.com,riskcontrol-inner.[RegionId].aliyuncs.com,riskcontrol.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "risk-cn-hangzhou.aliyuncs.com",
      "cn-beijing": "risk-cn-hangzhou.aliyuncs.com",
      "cn-beijing-inner": "risk-cn-hangzhou.aliyuncs.com",
      "cn-hangzhou": "risk-cn-hangzhou.aliyuncs.com",
      "cn-hangzhou-d": "risk-cn-hangzhou.aliyuncs.com",
      "cn-hongkong": "risk-cn-hangzhou.aliyuncs.com",
      "cn-qingdao": "risk-cn-hangzhou.aliyuncs.com",
      "cn-qingdao-cm9": "risk-cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "risk-cn-hangzhou.aliyuncs.com",
      "cn-shanghai-et2-b01": "risk-cn-hangzhou.aliyuncs.com",
      "cn-shanghai-inner": "risk-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen": "risk-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen-inner": "risk-cn-hangzhou.aliyuncs.com",
      "us-east-1": "risk-cn-hangzhou.aliyuncs.com",
      "us-west-1": "risk-cn-hangzhou.aliyuncs.com"
    }
  }, {
    "name": "Yundunoem",
    "major_version": "2017-03-24",
    "domain": "yundunoem-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Yunqi",
    "major_version": "2017-04-12",
    "domain": "yunqi.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "imm",
    "major_version": "2017-09-06",
    "domain": "imm.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "mrs-hcs",
    "major_version": "2017-06-17",
    "domain": "mrs-hcs.aliyuncs.com,mrs-hcs.[RegionId].aliyuncs.com,mrs-hcs-inner.aliyuncs.com,mrs-hcs-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "CloudDesk",
    "major_version": "2017-04-01",
    "domain": "ccs-inner.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Msg",
    "major_version": "2016-06-28",
    "domain": "msg-inner.aliyuncs.com,msg.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "msg-inner.aliyuncs.com",
      "cn-beijing": "msg-inner.aliyuncs.com",
      "cn-beijing-inner": "msg-inner.aliyuncs.com",
      "cn-hangzhou": "msg-inner.aliyuncs.com",
      "cn-hangzhou-d": "msg-inner.aliyuncs.com",
      "cn-hongkong": "msg-inner.aliyuncs.com",
      "cn-qingdao-cm9": "msg-inner.aliyuncs.com",
      "cn-shanghai": "msg-inner.aliyuncs.com",
      "cn-shanghai-et2-b01": "msg-inner.aliyuncs.com",
      "cn-shanghai-inner": "msg-inner.aliyuncs.com",
      "cn-shenzhen-inner": "msg-inner.aliyuncs.com",
      "us-east-1": "msg-inner.aliyuncs.com",
      "us-west-1": "msg-inner.aliyuncs.com"
    }
  }, {
    "name": "cloudwf",
    "major_version": "2017-03-28",
    "domain": "cloudwf.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Aas",
    "major_version": "2015-07-01",
    "domain": "aas.aliyuncs.com,aas-inner.aliyuncs.com,aas.[RegionId].aliyuncs.com,aas-inner.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "aas.aliyuncs.com",
      "cn-beijing": "aas.aliyuncs.com",
      "cn-beijing-inner": "aas.aliyuncs.com",
      "cn-hangzhou": "aas.aliyuncs.com",
      "cn-hangzhou-d": "aas.aliyuncs.com",
      "cn-hongkong": "aas.aliyuncs.com",
      "cn-qingdao": "aas.aliyuncs.com",
      "cn-qingdao-cm9": "aas.aliyuncs.com",
      "cn-shanghai": "aas.aliyuncs.com",
      "cn-shanghai-et2-b01": "aas.aliyuncs.com",
      "cn-shanghai-inner": "aas.aliyuncs.com",
      "cn-shenzhen": "aas.aliyuncs.com",
      "cn-shenzhen-inner": "aas.aliyuncs.com",
      "us-east-1": "aas.aliyuncs.com",
      "us-west-1": "aas.aliyuncs.com"
    }
  }, {
    "name": "Ecm",
    "major_version": "2017-04-15",
    "domain": "ecm.aliyuncs.com,ecm.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "IoT-service",
    "major_version": "2017-11-08",
    "domain": "omp-service-share.aliyuncs.com,omp-service-vpc.cn-shanghai.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Youhui-inner",
    "major_version": "2016-09-28",
    "domain": "youhui-cn-share.aliyuncs.com,youhui-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "hcs-mgw",
    "major_version": "2017-10-24",
    "domain": "mgw.aliyuncs.com,mgw.[RegionId].aliyuncs.com",
    "location_service_code": "hcs_mgw",
    "endpoints": {}
  }, {
    "name": "Ehs-inner",
    "major_version": "2017-10-13",
    "domain": "ehs-inner.aliyuncs.com,ehs-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Elasticsearch-Inner",
    "major_version": "2017-10-25",
    "domain": "elasticsearch-inner-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Ims",
    "major_version": "2017-04-30",
    "domain": "ims.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Edas",
    "major_version": "2017-08-01",
    "domain": "edas.aliyuncs.com,edas.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "RiskDataCenter",
    "major_version": "2017-07-25",
    "domain": "riskdatacenter-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Gxfw",
    "major_version": "2017-10-19",
    "domain": "gxfw-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Txapi",
    "major_version": "2017-11-08",
    "domain": "txapi-inner.aliyuncs.com,txapi-inner.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "havana",
    "major_version": "2016-09-20",
    "domain": "havana.aliyuncs.com,havana-share.aliyuncs.com,havana.[RegionId].aliyuncs.com,havana-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Alert-contact-inner",
    "major_version": "2016-03-16",
    "domain": "alert-contact-inner.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Cdn-inner",
    "major_version": "2016-12-12",
    "domain": "cdn-inc.aliyuncs.com,cdn-inc-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Dyvms",
    "major_version": "2017-06-20",
    "domain": "dyvms.aliyuncs.com,dyvms.[RegionId].aliyuncs.com,dyvms-cn-shagnhai.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "HighDDos",
    "major_version": "2017-09-20",
    "domain": "yd-highddos-cn-hangzhou.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "yd-highddos-cn-hangzhou.aliyuncs.com",
      "cn-beijing": "yd-highddos-cn-hangzhou.aliyuncs.com",
      "cn-beijing-inner": "yd-highddos-cn-hangzhou.aliyuncs.com",
      "cn-hangzhou": "yd-highddos-cn-hangzhou.aliyuncs.com",
      "cn-hangzhou-d": "yd-highddos-cn-hangzhou.aliyuncs.com",
      "cn-hongkong": "yd-highddos-cn-hangzhou.aliyuncs.com",
      "cn-qingdao": "yd-highddos-cn-hangzhou.aliyuncs.com",
      "cn-qingdao-cm9": "yd-highddos-cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "yd-highddos-cn-hangzhou.aliyuncs.com",
      "cn-shanghai-et2-b01": "yd-highddos-cn-hangzhou.aliyuncs.com",
      "cn-shanghai-inner": "yd-highddos-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen": "yd-highddos-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen-inner": "yd-highddos-cn-hangzhou.aliyuncs.com",
      "us-east-1": "yd-highddos-cn-hangzhou.aliyuncs.com",
      "us-west-1": "yd-highddos-cn-hangzhou.aliyuncs.com"
    }
  }, {
    "name": "waf",
    "major_version": "2016-07-18",
    "domain": "yw.aliyuncs.com,waf-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "avds",
    "major_version": "2017-11-29",
    "domain": "avds.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "BssOpenApi",
    "major_version": "2017-12-14",
    "domain": "business.aliyuncs.com,business.ap-southeast-1.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Phoenixsp",
    "major_version": "2015-08-25",
    "domain": "phoenixsp.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "aegis-ops",
    "major_version": "2017-02-21",
    "domain": "aegis-inner.aliyuncs.com,aegis-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Partner",
    "major_version": "2017-01-01",
    "domain": "partner.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "axt",
    "major_version": "2017-07-31",
    "domain": "axt-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "yundun-service",
    "major_version": "2016-04-28",
    "domain": "yundun-service-internal.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Consolecs",
    "major_version": "2016-04-06",
    "domain": "consolecs.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "HBase",
    "major_version": "2017-01-15",
    "domain": "hbase.aliyuncs.com,hbase.[RegionId].aliyuncs.com,hbase-share.aliyuncs.com,hbase-share.[RegionId].aliyuncs.com",
    "location_service_code": "hbase",
    "endpoints": {}
  }, {
    "name": "Ons",
    "major_version": "2016-05-03",
    "domain": "ons.aliyuncs.com,ons.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "ons.aliyuncs.com",
      "cn-beijing": "ons.aliyuncs.com",
      "cn-beijing-inner": "ons.aliyuncs.com",
      "cn-hangzhou": "ons.aliyuncs.com",
      "cn-hangzhou-d": "ons.aliyuncs.com",
      "cn-hongkong": "ons.aliyuncs.com",
      "cn-qingdao": "ons.aliyuncs.com",
      "cn-qingdao-cm9": "ons.aliyuncs.com",
      "cn-shanghai": "ons.aliyuncs.com",
      "cn-shanghai-et2-b01": "ons.aliyuncs.com",
      "cn-shanghai-inner": "ons.aliyuncs.com",
      "cn-shenzhen": "ons.aliyuncs.com",
      "cn-shenzhen-inner": "ons.aliyuncs.com",
      "us-east-1": "ons.aliyuncs.com",
      "us-west-1": "ons.aliyuncs.com"
    }
  }, {
    "name": "Location",
    "major_version": "2015-06-12",
    "domain": "location.aliyuncs.com,location-readonly.aliyuncs.com,location.[RegionId].aliyuncs.com,location-center.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "location.aliyuncs.com",
      "cn-beijing": "location.aliyuncs.com",
      "cn-beijing-inner": "location.aliyuncs.com",
      "cn-hangzhou": "location.aliyuncs.com",
      "cn-hangzhou-d": "location.aliyuncs.com",
      "cn-hongkong": "location.aliyuncs.com",
      "cn-qingdao": "location.aliyuncs.com",
      "cn-qingdao-cm9": "location.aliyuncs.com",
      "cn-shanghai": "location.aliyuncs.com",
      "cn-shanghai-et2-b01": "location.aliyuncs.com",
      "cn-shanghai-inner": "location.aliyuncs.com",
      "cn-shenzhen": "location.aliyuncs.com",
      "cn-shenzhen-inner": "location.aliyuncs.com",
      "us-east-1": "location.aliyuncs.com",
      "us-west-1": "location.aliyuncs.com"
    }
  }, {
    "name": "live-inner",
    "major_version": "2016-11-01",
    "domain": "live-inner.aliyuncs.com,live-inner.[RegionId].aliyuncs.com,live-inc-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "SWAS",
    "major_version": "2017-08-10",
    "domain": "sas-share.[RegionId].aliyuncs.com,swas-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Zhuque",
    "major_version": "2016-07-01",
    "domain": "cpp-inner.aliyuncs.com,zhuque-inner.aliyuncs.com,zhuque-inner.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Biz-ipdb",
    "major_version": "2016-08-08",
    "domain": "bizipdb-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Ecs",
    "major_version": "2014-05-26",
    "domain": "ecs-cn-hangzhou.aliyuncs.com,ecs.[RegionId].aliyuncs.com,ecs-openapi-inner.[RegionId].aliyuncs.com,ecs-openapi-share.[RegionId].aliyuncs.com,ecs-taiwan.aliyuncs.com,ecs-cn-hangzhou-inner.aliyuncs.com,ecs-in-west-antgroup-1.aliyuncs.com,ecs-in-west-antgroup-2.aliyuncs.com,ecs-cn-hangzhou-share.aliyuncs.com,ecs.aliyuncs.com",
    "location_service_code": "ecs",
    "endpoints": {
      "ap-northeast-1": "ecs.ap-northeast-1.aliyuncs.com",
      "ap-southeast-1": "ecs-cn-hangzhou.aliyuncs.com",
      "ap-southeast-2": "ecs.ap-southeast-2.aliyuncs.com",
      "ap-southeast-antgroup-1": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-anhui-gov": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-anhui-gov-1": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-beijing": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-beijing-am13-c01": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-beijing-inner": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-beijing-nu16-b01": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-fujian": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-gansu-am6": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-guizhou": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-guizhou-gov": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-haidian-cm12-c01": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-hangzhou": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-hangzhou-bj-b01": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-hangzhou-d": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-henan-am12001": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-hongkong": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-ningxia-am7-c01": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-ningxiazhongwei": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-qingdao": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-qingdao-cm9": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-shanghai-et2-b01": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-shanghai-finance-1": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-shanghai-inner": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen-finance-1": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen-inner": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen-st4-d01": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen-su18-b01": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen-su18-b02": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen-su18-b03": "ecs-cn-hangzhou.aliyuncs.com",
      "cn-zhangjiakou": "ecs.cn-zhangjiakou.aliyuncs.com",
      "eu-central-1": "ecs.eu-central-1.aliyuncs.com",
      "in-mumbai-alipay": "ecs-cn-hangzhou.aliyuncs.com",
      "in-west-antgroup-1": "ecs-cn-hangzhou.aliyuncs.com",
      "in-west-antgroup-2": "ecs-cn-hangzhou.aliyuncs.com",
      "jp-fudao-1": "ecs-cn-hangzhou.aliyuncs.com",
      "me-east-1": "ecs.me-east-1.aliyuncs.com",
      "tw-snowcloud-kaohsiung": "ecs-cn-hangzhou.aliyuncs.com",
      "us-east-1": "ecs-cn-hangzhou.aliyuncs.com",
      "us-west-1": "ecs-cn-hangzhou.aliyuncs.com"
    }
  }, {
    "name": "RdcBuy",
    "major_version": "2017-10-19",
    "domain": "rdc-buy-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "vae",
    "major_version": "2016-10-13",
    "domain": "vae.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "CreditService-Inner",
    "major_version": "2017-06-15",
    "domain": "credit-inner.aliyuncs.com,credit-inner-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Lx",
    "major_version": "2015-07-01",
    "domain": "lx.aliyuncs.com,lx-inner.aliyuncs.com,lx-intl.aliyuncs.com,lx-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "SolutionSuperDriver",
    "major_version": "2017-01-01",
    "domain": "superdriver-inner.aliyuncs.com,superdriver-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "aegis",
    "major_version": "2016-11-11",
    "domain": "aegis.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "account-crm",
    "major_version": "2016-06-06",
    "domain": "account-crm.aliyuncs.com,account-crm-share.aliyuncs.com,account-crm.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "jaq",
    "major_version": "2016-11-23",
    "domain": "jaq.aliyuncs.com,jaq-share.aliyuncs.com,jaq.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "jaq.aliyuncs.com",
      "cn-beijing": "jaq.aliyuncs.com",
      "cn-beijing-inner": "jaq.aliyuncs.com",
      "cn-hangzhou": "jaq.aliyuncs.com",
      "cn-hangzhou-d": "jaq.aliyuncs.com",
      "cn-hongkong": "jaq.aliyuncs.com",
      "cn-qingdao": "jaq.aliyuncs.com",
      "cn-qingdao-cm9": "jaq.aliyuncs.com",
      "cn-shanghai": "jaq.aliyuncs.com",
      "cn-shanghai-et2-b01": "jaq.aliyuncs.com",
      "cn-shanghai-inner": "jaq.aliyuncs.com",
      "cn-shenzhen": "jaq.aliyuncs.com",
      "cn-shenzhen-inner": "jaq.aliyuncs.com",
      "us-east-1": "jaq.aliyuncs.com",
      "us-west-1": "jaq.aliyuncs.com"
    }
  }, {
    "name": "quickbi",
    "major_version": "2016-07-07",
    "domain": "quickbi-inner.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "AMS",
    "major_version": "2016-02-01",
    "domain": "ams.aliyuncs.com,ams-inner.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "ams.aliyuncs.com",
      "cn-beijing": "ams.aliyuncs.com",
      "cn-beijing-inner": "ams.aliyuncs.com",
      "cn-hangzhou": "ams.aliyuncs.com",
      "cn-hangzhou-d": "ams.aliyuncs.com",
      "cn-hongkong": "ams.aliyuncs.com",
      "cn-qingdao-cm9": "ams.aliyuncs.com",
      "cn-shanghai": "ams.aliyuncs.com",
      "cn-shanghai-et2-b01": "ams.aliyuncs.com",
      "cn-shanghai-inner": "ams.aliyuncs.com",
      "cn-shenzhen-inner": "ams.aliyuncs.com",
      "us-east-1": "ams.aliyuncs.com",
      "us-west-1": "ams.aliyuncs.com"
    }
  }, {
    "name": "CS",
    "major_version": "2015-12-15",
    "domain": "cs.aliyuncs.com,cs-anony.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "cs.aliyuncs.com",
      "cn-beijing": "cs.aliyuncs.com",
      "cn-beijing-inner": "cs.aliyuncs.com",
      "cn-hangzhou": "cs.aliyuncs.com",
      "cn-hangzhou-d": "cs.aliyuncs.com",
      "cn-hongkong": "cs.aliyuncs.com",
      "cn-qingdao": "cs.aliyuncs.com",
      "cn-qingdao-cm9": "cs.aliyuncs.com",
      "cn-shanghai": "cs.aliyuncs.com",
      "cn-shanghai-et2-b01": "cs.aliyuncs.com",
      "cn-shanghai-inner": "cs.aliyuncs.com",
      "cn-shenzhen": "cs.aliyuncs.com",
      "cn-shenzhen-inner": "cs.aliyuncs.com",
      "us-east-1": "cs.aliyuncs.com",
      "us-west-1": "cs.aliyuncs.com"
    }
  }, {
    "name": "Oam",
    "major_version": "2017-01-01",
    "domain": "oam.aliyuncs.com,oam-share.aliyuncs.com,oam-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "cert",
    "major_version": "2016-03-01",
    "domain": "cert.aliyuncs.com,cert.[RegionId].aliyuncs.com,cert-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "hjsyncgw",
    "major_version": "2017-01-05",
    "domain": "hjsyncgw.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Mts",
    "major_version": "2014-06-18",
    "domain": "mts.aliyuncs.com,mts.[RegionId].aliyuncs.com,youku-mts.cn-shanghai.aliyuncs.com,mts-vpc.[RegionId].aliyuncs.com",
    "location_service_code": "mts",
    "endpoints": {
      "ap-southeast-1": "mts.ap-southeast-1.aliyuncs.com",
      "cn-beijing": "mts.cn-beijing.aliyuncs.com",
      "cn-beijing-inner": "mts.cn-beijing.aliyuncs.com",
      "cn-hangzhou": "mts.cn-hangzhou.aliyuncs.com",
      "cn-hangzhou-d": "mts.cn-hangzhou.aliyuncs.com",
      "cn-hongkong": "mts.cn-hongkong.aliyuncs.com",
      "cn-qingdao": "mts.cn-qingdao.aliyuncs.com",
      "cn-qingdao-cm9": "mts.cn-qingdao.aliyuncs.com",
      "cn-shanghai": "mts.cn-shanghai.aliyuncs.com",
      "cn-shanghai-et2-b01": "mts.cn-hangzhou.aliyuncs.com",
      "cn-shanghai-inner": "mts.cn-shanghai.aliyuncs.com",
      "cn-shenzhen": "mts.cn-shenzhen.aliyuncs.com",
      "cn-shenzhen-inner": "mts.cn-shenzhen.aliyuncs.com",
      "us-west-1": "mts.us-west-1.aliyuncs.com"
    }
  }, {
    "name": "Qualitycheck",
    "major_version": "2016-08-01",
    "domain": "qualitycheck.aliyuncs.com,qualitycheck.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "qualitycheck.aliyuncs.com",
      "cn-beijing-inner": "qualitycheck.aliyuncs.com",
      "cn-hangzhou": "qualitycheck.aliyuncs.com",
      "cn-hangzhou-d": "qualitycheck.aliyuncs.com",
      "cn-hongkong": "qualitycheck.aliyuncs.com",
      "cn-qingdao-cm9": "qualitycheck.aliyuncs.com",
      "cn-shanghai": "qualitycheck.aliyuncs.com",
      "cn-shanghai-et2-b01": "qualitycheck.aliyuncs.com",
      "cn-shanghai-inner": "qualitycheck.aliyuncs.com",
      "cn-shenzhen-inner": "qualitycheck.aliyuncs.com",
      "us-east-1": "qualitycheck.aliyuncs.com",
      "us-west-1": "qualitycheck.aliyuncs.com"
    }
  }, {
    "name": "ddosbgp",
    "major_version": "2017-11-20",
    "domain": "ddosbgp.[RegionId].aliyuncs.com",
    "location_service_code": "ddosbgp",
    "endpoints": {}
  }, {
    "name": "gpdb",
    "major_version": "2016-05-03",
    "domain": "gpdb.aliyuncs.com,gpdb.[RegionId].aliyuncs.com",
    "location_service_code": "gpdb",
    "endpoints": {}
  }, {
    "name": "scdn-inner",
    "major_version": "2017-07-27",
    "domain": "scdn-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "yundun-aegis-service",
    "major_version": "2016-07-12",
    "domain": "yundun-aegisbiz-service-internal.aliyuncs.com,yundun-aegis-service-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "RdsForInner",
    "major_version": "2016-01-01",
    "domain": "rds-inner.[RegionId].aliyuncs.com,rds-share.aliyuncs.com,rds-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Babel",
    "major_version": "2016-07-15",
    "domain": "babel.aliyuncs.com,babel-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Cosmo",
    "major_version": "2017-07-28",
    "domain": "cosmo.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Intlaccount-inner",
    "major_version": "2016-10-24",
    "domain": "intlaccount-cn-share.aliyuncs.com,intlaccount-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "ROS",
    "major_version": "2015-09-01",
    "domain": "ros.aliyuncs.com,ros-inner.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "ros.aliyuncs.com",
      "cn-beijing": "ros.aliyuncs.com",
      "cn-beijing-inner": "ros.aliyuncs.com",
      "cn-hangzhou": "ros.aliyuncs.com",
      "cn-hangzhou-d": "ros.aliyuncs.com",
      "cn-hongkong": "ros.aliyuncs.com",
      "cn-qingdao": "ros.aliyuncs.com",
      "cn-qingdao-cm9": "ros.aliyuncs.com",
      "cn-shanghai": "ros.aliyuncs.com",
      "cn-shanghai-et2-b01": "ros.aliyuncs.com",
      "cn-shanghai-inner": "ros.aliyuncs.com",
      "cn-shenzhen": "ros.aliyuncs.com",
      "cn-shenzhen-inner": "ros.aliyuncs.com",
      "us-east-1": "ros.aliyuncs.com",
      "us-west-1": "ros.aliyuncs.com"
    }
  }, {
    "name": "TeslaMaxCompute",
    "major_version": "2017-11-30",
    "domain": "teslamaxcompute.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Babel-public",
    "major_version": "2016-07-15",
    "domain": "babel-public.aliyuncs.com,babel-public.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Cbn",
    "major_version": "2017-09-12",
    "domain": "cbn.aliyuncs.com,cbn.[RegionId].aliyuncs.com",
    "location_service_code": "cbn",
    "endpoints": {}
  }, {
    "name": "Emr",
    "major_version": "2016-04-08",
    "domain": "emr.aliyuncs.com,emr.[RegionId].aliyuncs.com,emr-inner.aliyuncs.com",
    "location_service_code": "emr",
    "endpoints": {
      "ap-southeast-1": "emr.aliyuncs.com",
      "cn-beijing": "emr.aliyuncs.com",
      "cn-beijing-inner": "emr.aliyuncs.com",
      "cn-hangzhou": "emr.aliyuncs.com",
      "cn-hangzhou-d": "emr.aliyuncs.com",
      "cn-hongkong": "emr.aliyuncs.com",
      "cn-qingdao": "emr.cn-qingdao.aliyuncs.com",
      "cn-qingdao-cm9": "emr.aliyuncs.com",
      "cn-shanghai": "emr.aliyuncs.com",
      "cn-shanghai-et2-b01": "emr.aliyuncs.com",
      "cn-shanghai-inner": "emr.aliyuncs.com",
      "cn-shenzhen": "emr.aliyuncs.com",
      "cn-shenzhen-inner": "emr.aliyuncs.com",
      "cn-zhangjiakou": "emr.cn-zhangjiakou.aliyuncs.com",
      "eu-central-1": "emr.eu-central-1.aliyuncs.com",
      "us-east-1": "emr.aliyuncs.com",
      "us-west-1": "emr.aliyuncs.com"
    }
  }, {
    "name": "Ess",
    "major_version": "2014-08-28",
    "domain": "ess.aliyuncs.com,ess.[RegionId].aliyuncs.com",
    "location_service_code": "ess",
    "endpoints": {
      "ap-southeast-1": "ess.aliyuncs.com",
      "cn-beijing": "ess.aliyuncs.com",
      "cn-beijing-inner": "ess.aliyuncs.com",
      "cn-hangzhou": "ess.aliyuncs.com",
      "cn-hangzhou-d": "ess.aliyuncs.com",
      "cn-hongkong": "ess.aliyuncs.com",
      "cn-qingdao": "ess.aliyuncs.com",
      "cn-qingdao-cm9": "ess.aliyuncs.com",
      "cn-shanghai": "ess.aliyuncs.com",
      "cn-shanghai-et2-b01": "ess.aliyuncs.com",
      "cn-shanghai-inner": "ess.aliyuncs.com",
      "cn-shenzhen": "ess.aliyuncs.com",
      "cn-shenzhen-inner": "ess.aliyuncs.com",
      "us-east-1": "ess.aliyuncs.com",
      "us-west-1": "ess.aliyuncs.com"
    }
  }, {
    "name": "hk-HighDDos",
    "major_version": "2016-04-10",
    "domain": "yd-highddos-cn-hongkong.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "polardb4inner",
    "major_version": "2017-08-01",
    "domain": "polardb4inner.aliyuncs.com,polardb4inner.[RegionId].aliyuncs.com,polardb4inner-inner.aliyuncs.com,polardb4inner-inner.[RegionId].aliyuncs.com,polardb4inner-share.aliyuncs.com,polardb4inner-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "eas",
    "major_version": "2017-10-23",
    "domain": "eas.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Bss",
    "major_version": "2014-07-14",
    "domain": "bss.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "bss.aliyuncs.com",
      "cn-beijing": "bss.aliyuncs.com",
      "cn-beijing-inner": "bss.aliyuncs.com",
      "cn-hangzhou": "bss.aliyuncs.com",
      "cn-hangzhou-d": "bss.aliyuncs.com",
      "cn-hongkong": "bss.aliyuncs.com",
      "cn-qingdao": "bss.aliyuncs.com",
      "cn-qingdao-cm9": "bss.aliyuncs.com",
      "cn-shanghai": "bss.aliyuncs.com",
      "cn-shanghai-et2-b01": "bss.aliyuncs.com",
      "cn-shanghai-inner": "bss.aliyuncs.com",
      "cn-shenzhen": "bss.aliyuncs.com",
      "cn-shenzhen-inner": "bss.aliyuncs.com",
      "us-east-1": "bss.aliyuncs.com",
      "us-west-1": "bss.aliyuncs.com"
    }
  }, {
    "name": "DdsInner",
    "major_version": "2015-12-01",
    "domain": "mongodb-internal.aliyuncs.com,mongodb-inc-share.aliyuncs.com,mongodb-inc-share.[RegionId].aliyuncs.com,mongdb-inc-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Ocs",
    "major_version": "2015-03-01",
    "domain": "pop-ocs.aliyuncs.com,m-kvstore.aliyuncs.com,m-kvstore.[RegionId].aliyuncs.com,pop-ocs-inner.aliyuncs.com,m-kvstore-in-west-antgroup-1.aliyuncs.com,m-kvstore-in-west-antgroup-2.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "m-kvstore.aliyuncs.com",
      "cn-beijing": "m-kvstore.aliyuncs.com",
      "cn-beijing-inner": "m-kvstore.aliyuncs.com",
      "cn-hangzhou": "m-kvstore.aliyuncs.com",
      "cn-hangzhou-d": "m-kvstore.aliyuncs.com",
      "cn-hongkong": "m-kvstore.aliyuncs.com",
      "cn-qingdao": "m-kvstore.aliyuncs.com",
      "cn-qingdao-cm9": "m-kvstore.aliyuncs.com",
      "cn-shanghai": "m-kvstore.aliyuncs.com",
      "cn-shanghai-et2-b01": "m-kvstore.aliyuncs.com",
      "cn-shanghai-inner": "m-kvstore.aliyuncs.com",
      "cn-shenzhen": "m-kvstore.aliyuncs.com",
      "cn-shenzhen-inner": "m-kvstore.aliyuncs.com",
      "us-east-1": "m-kvstore.aliyuncs.com",
      "us-west-1": "m-kvstore.aliyuncs.com"
    }
  }, {
    "name": "Cloudauth",
    "major_version": "2017-10-10",
    "domain": "cloudauth.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "oceanbase",
    "major_version": "2016-02-29",
    "domain": "oceanbase.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "oceanbase.aliyuncs.com",
      "cn-beijing": "oceanbase.aliyuncs.com",
      "cn-beijing-inner": "oceanbase.aliyuncs.com",
      "cn-hangzhou": "oceanbase.aliyuncs.com",
      "cn-hangzhou-d": "oceanbase.aliyuncs.com",
      "cn-hongkong": "oceanbase.aliyuncs.com",
      "cn-qingdao": "oceanbase.aliyuncs.com",
      "cn-qingdao-cm9": "oceanbase.aliyuncs.com",
      "cn-shanghai": "oceanbase.aliyuncs.com",
      "cn-shanghai-et2-b01": "oceanbase.aliyuncs.com",
      "cn-shanghai-inner": "oceanbase.aliyuncs.com",
      "cn-shenzhen": "oceanbase.aliyuncs.com",
      "cn-shenzhen-inner": "oceanbase.aliyuncs.com",
      "us-east-1": "oceanbase.aliyuncs.com",
      "us-west-1": "oceanbase.aliyuncs.com"
    }
  }, {
    "name": "Beian",
    "major_version": "2016-08-10",
    "domain": "beian-inner.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "CloudCallCenter",
    "major_version": "2017-07-05",
    "domain": "ccc-inner-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "CloudComm",
    "major_version": "2017-06-20",
    "domain": "cloudcomm.aliyuncs.com,cloudcomm.[RegionId].aliyuncs.com,cloudcomm-cn-shagnhai.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "EmrAdmin",
    "major_version": "2016-07-18",
    "domain": "emradmin.cn-hangzhou.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "DDoSProInc",
    "major_version": "2017-12-20",
    "domain": "ddospro-inc-share.aliyuncs.com,ddospro-inc-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Dypls",
    "major_version": "2017-08-30",
    "domain": "dypls.aliyuncs.com,dypls.[RegionId].aliyuncs.com,dypls-cn-shagnhai.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Dyplsapi",
    "major_version": "2017-05-25",
    "domain": "dyplsapi.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "alimail-console-inner",
    "major_version": "2017-03-01",
    "domain": "alimail-console-inner.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Dts-inner",
    "major_version": "2016-03-16",
    "domain": "dts-inner.aliyuncs.com,dts-inner.[RegionId].aliyuncs.com,dts-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "ITaaS",
    "major_version": "2017-05-09",
    "domain": "itaas.aliyuncs.com,itaas.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Oms",
    "major_version": "2016-06-15",
    "domain": "oms.aliyuncs.com,oms-taiwan.aliyuncs.com,oms-inner.aliyuncs.com,oms-share.aliyuncs.com,oms-inner.[RegionId].aliyuncs.com,oms-share.[RegionId].aliyuncs.com,oms.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "oms.aliyuncs.com",
      "cn-beijing": "oms.aliyuncs.com",
      "cn-beijing-inner": "oms.aliyuncs.com",
      "cn-hangzhou": "oms.aliyuncs.com",
      "cn-hangzhou-d": "oms.aliyuncs.com",
      "cn-hongkong": "oms.aliyuncs.com",
      "cn-qingdao": "oms.aliyuncs.com",
      "cn-qingdao-cm9": "oms.aliyuncs.com",
      "cn-shanghai": "oms.aliyuncs.com",
      "cn-shanghai-et2-b01": "oms.aliyuncs.com",
      "cn-shanghai-inner": "oms.aliyuncs.com",
      "cn-shenzhen": "oms.aliyuncs.com",
      "cn-shenzhen-inner": "oms.aliyuncs.com",
      "us-east-1": "oms.aliyuncs.com",
      "us-west-1": "oms.aliyuncs.com"
    }
  }, {
    "name": "yundun-bwaf",
    "major_version": "2017-03-15",
    "domain": "bwaf-share.aliyuncs.com,bwaf-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Hosting",
    "major_version": "2016-10-09",
    "domain": "hosting.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Signin",
    "major_version": "2017-10-01",
    "domain": "signin.aliyuncs.com,signin.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "adbForInner",
    "major_version": "2016-12-12",
    "domain": "adb-inner.aliyuncs.com,adb.aliyuncs.com,adb-share.aliyuncs.com,adb-share.[RegionId].aliyuncs.com,adb-inner.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Ubsms-inner",
    "major_version": "2015-06-23",
    "domain": "ubsms-inner.aliyuncs.com,ubsms-share.aliyuncs.com,ubsms-inner.[RegionId].aliyuncs.com,ubsms-share.[RegionId].aliyuncs.com,ubsms-inner1.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "ubsms-inner.aliyuncs.com",
      "cn-beijing": "ubsms-inner.aliyuncs.com",
      "cn-beijing-inner": "ubsms-inner.aliyuncs.com",
      "cn-hangzhou": "ubsms-inner.aliyuncs.com",
      "cn-hangzhou-d": "ubsms-inner.aliyuncs.com",
      "cn-hongkong": "ubsms-inner.aliyuncs.com",
      "cn-qingdao": "ubsms-inner.cn-qingdao.aliyuncs.com",
      "cn-qingdao-cm9": "ubsms-inner.aliyuncs.com",
      "cn-shanghai": "ubsms-inner.aliyuncs.com",
      "cn-shanghai-et2-b01": "ubsms-inner.aliyuncs.com",
      "cn-shanghai-inner": "ubsms-inner.aliyuncs.com",
      "cn-shenzhen": "ubsms-inner.aliyuncs.com",
      "cn-shenzhen-inner": "ubsms-inner.aliyuncs.com",
      "us-east-1": "ubsms-inner.aliyuncs.com",
      "us-west-1": "ubsms-inner.aliyuncs.com"
    }
  }, {
    "name": "ADS",
    "major_version": "2016-09-08",
    "domain": "ads.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Rds",
    "major_version": "2014-08-15",
    "domain": "rds.[RegionId].aliyuncs.com,rds-cn-hangzhou.aliyuncs.com,rds.aliyuncs.com,rds-taiwan.aliyuncs.com,rds-cn-hangzhou-inner.aliyuncs.com,rds-in-west-antgroup-1.aliyuncs.com,rds-in-west-antgroup-2.aliyuncs.com,rds-inc-share.aliyuncs.com,rds-inc-share.[RegionId].aliyuncs.com",
    "location_service_code": "rds",
    "endpoints": {
      "ap-northeast-1": "rds.ap-northeast-1.aliyuncs.com",
      "ap-southeast-1": "rds.aliyuncs.com",
      "ap-southeast-2": "rds.ap-southeast-2.aliyuncs.com",
      "cn-beijing": "rds.aliyuncs.com",
      "cn-beijing-gov-1": "rds.aliyuncs.com",
      "cn-beijing-inner": "rds.aliyuncs.com",
      "cn-fujian": "rds.aliyuncs.com",
      "cn-gansu-am6": "rds.aliyuncs.com",
      "cn-haidian-cm12-c01": "rds.aliyuncs.com",
      "cn-hangzhou": "rds.aliyuncs.com",
      "cn-hangzhou-d": "rds.aliyuncs.com",
      "cn-hongkong": "rds.aliyuncs.com",
      "cn-qingdao": "rds.aliyuncs.com",
      "cn-qingdao-cm9": "rds.aliyuncs.com",
      "cn-shanghai": "rds.aliyuncs.com",
      "cn-shanghai-et2-b01": "rds.aliyuncs.com",
      "cn-shanghai-finance-1": "rds.aliyuncs.com",
      "cn-shanghai-inner": "rds.aliyuncs.com",
      "cn-shenzhen": "rds.aliyuncs.com",
      "cn-shenzhen-finance-1": "rds.aliyuncs.com",
      "cn-shenzhen-inner": "rds.aliyuncs.com",
      "cn-zhangjiakou": "rds.cn-zhangjiakou.aliyuncs.com",
      "eu-central-1": "rds.eu-central-1.aliyuncs.com",
      "me-east-1": "rds.me-east-1.aliyuncs.com",
      "us-east-1": "rds.aliyuncs.com",
      "us-west-1": "rds.aliyuncs.com"
    }
  }, {
    "name": "ThreatInfoProduct",
    "major_version": "2016-09-19",
    "domain": "threatinfo.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "CloudPhoto",
    "major_version": "2017-07-11",
    "domain": "cloudphoto.aliyuncs.com,cloudphoto.[RegionId].aliyuncs.com,cloudphoto-pre.[RegionId].aliyuncs.com",
    "location_service_code": "cloudphoto",
    "endpoints": {}
  }, {
    "name": "Domain-inner",
    "major_version": "2016-09-19",
    "domain": "domain-inner.aliyuncs.com,domain-inc-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "apigateway-inner",
    "major_version": "2017-04-01",
    "domain": "apigateway-inner.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Slb",
    "major_version": "2014-05-15",
    "domain": "slb.aliyuncs.com,slb-pop.aliyuncs.com,slb-taiwan.aliyuncs.com,slb-pop-inner.aliyuncs.com,slb-in-west-antgroup-1.aliyuncs.com,slb-in-west-antgroup-2.aliyuncs.com,slb.[RegionId].aliyuncs.com,slb-openapi-share.[RegionId].aliyuncs.com,slb-openapi-share.aliyuncs.com",
    "location_service_code": "slb",
    "endpoints": {
      "ap-northeast-1": "slb.ap-northeast-1.aliyuncs.com",
      "ap-southeast-1": "slb.aliyuncs.com",
      "ap-southeast-2": "slb.ap-southeast-2.aliyuncs.com",
      "cn-beijing": "slb.aliyuncs.com",
      "cn-beijing-inner": "slb.aliyuncs.com",
      "cn-hangzhou": "slb.aliyuncs.com",
      "cn-hangzhou-d": "slb.aliyuncs.com",
      "cn-hongkong": "slb.aliyuncs.com",
      "cn-qingdao": "slb.aliyuncs.com",
      "cn-qingdao-cm9": "slb.aliyuncs.com",
      "cn-shanghai": "slb.aliyuncs.com",
      "cn-shanghai-et2-b01": "slb.aliyuncs.com",
      "cn-shanghai-inner": "slb.aliyuncs.com",
      "cn-shenzhen": "slb.aliyuncs.com",
      "cn-shenzhen-inner": "slb.aliyuncs.com",
      "cn-zhangjiakou": "slb.cn-zhangjiakou.aliyuncs.com",
      "eu-central-1": "slb.eu-central-1.aliyuncs.com",
      "me-east-1": "slb.me-east-1.aliyuncs.com",
      "us-east-1": "slb.aliyuncs.com",
      "us-west-1": "slb.aliyuncs.com"
    }
  }, {
    "name": "Slb-inner",
    "major_version": "2014-05-15",
    "domain": "slb-inner.aliyuncs.com,slb-inner.[RegionId].aliyuncs.com,slb-share.aliyuncs.com,slb-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Sales",
    "major_version": "2017-03-10",
    "domain": "sales.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "sales.cn-hangzhou.aliyuncs.com",
      "cn-beijing": "sales.cn-hangzhou.aliyuncs.com",
      "cn-beijing-inner": "sales.cn-hangzhou.aliyuncs.com",
      "cn-hangzhou": "sales.cn-hangzhou.aliyuncs.com",
      "cn-hangzhou-d": "sales.cn-hangzhou.aliyuncs.com",
      "cn-hongkong": "sales.cn-hangzhou.aliyuncs.com",
      "cn-qingdao-cm9": "sales.cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "sales.cn-hangzhou.aliyuncs.com",
      "cn-shanghai-et2-b01": "sales.cn-hangzhou.aliyuncs.com",
      "cn-shanghai-inner": "sales.cn-hangzhou.aliyuncs.com",
      "cn-shenzhen-inner": "sales.cn-hangzhou.aliyuncs.com",
      "us-east-1": "sales.cn-hangzhou.aliyuncs.com",
      "us-west-1": "sales.cn-hangzhou.aliyuncs.com"
    }
  }, {
    "name": "YundunDdos",
    "major_version": "2016-05-11",
    "domain": "inner-yundun-ddos.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "inner-yundun-ddos.cn-hangzhou.aliyuncs.com",
      "cn-beijing": "inner-yundun-ddos.cn-hangzhou.aliyuncs.com",
      "cn-beijing-inner": "inner-yundun-ddos.cn-hangzhou.aliyuncs.com",
      "cn-hangzhou": "inner-yundun-ddos.cn-hangzhou.aliyuncs.com",
      "cn-hangzhou-d": "inner-yundun-ddos.cn-hangzhou.aliyuncs.com",
      "cn-hongkong": "inner-yundun-ddos.cn-hangzhou.aliyuncs.com",
      "cn-qingdao-cm9": "inner-yundun-ddos.cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "inner-yundun-ddos.cn-hangzhou.aliyuncs.com",
      "cn-shanghai-et2-b01": "inner-yundun-ddos.cn-hangzhou.aliyuncs.com",
      "cn-shanghai-inner": "inner-yundun-ddos.cn-hangzhou.aliyuncs.com",
      "cn-shenzhen-inner": "inner-yundun-ddos.cn-hangzhou.aliyuncs.com",
      "us-east-1": "inner-yundun-ddos.cn-hangzhou.aliyuncs.com",
      "us-west-1": "inner-yundun-ddos.cn-hangzhou.aliyuncs.com"
    }
  }, {
    "name": "gpu_cgs",
    "major_version": "2017-11-02",
    "domain": "gpu-cgs-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "CloudAPI",
    "major_version": "2016-02-01",
    "domain": "apigateway.aliyuncs.com,apigateway-inner.aliyuncs.com,apigateway.[RegionId].aliyuncs.com",
    "location_service_code": "apigateway",
    "endpoints": {
      "ap-southeast-1": "apigateway.ap-southeast-1.aliyuncs.com",
      "cn-beijing": "apigateway.cn-beijing.aliyuncs.com",
      "cn-hangzhou": "apigateway.cn-hangzhou.aliyuncs.com",
      "cn-hongkong": "apigateway.cn-hongkong.aliyuncs.com",
      "cn-qingdao": "apigateway.cn-qingdao.aliyuncs.com",
      "cn-shanghai": "apigateway.cn-shanghai.aliyuncs.com",
      "cn-shenzhen": "apigateway.cn-shenzhen.aliyuncs.com"
    }
  }, {
    "name": "Coupon",
    "major_version": "2017-01-01",
    "domain": "coupon.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Dycdp",
    "major_version": "2017-06-20",
    "domain": "dycdp.aliyuncs.com,dycdp.[RegionId].aliyuncs.com,dycdp-cn-shagnhai.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "DDoSPro",
    "major_version": "2017-12-20",
    "domain": "ddospro.aliyuncs.com,ddospro.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Dm",
    "major_version": "2015-11-23",
    "domain": "dm.aliyuncs.com,dm.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "dm.aliyuncs.com",
      "cn-beijing": "dm.aliyuncs.com",
      "cn-beijing-inner": "dm.aliyuncs.com",
      "cn-hangzhou": "dm.aliyuncs.com",
      "cn-hangzhou-d": "dm.aliyuncs.com",
      "cn-hongkong": "dm.aliyuncs.com",
      "cn-qingdao": "dm.aliyuncs.com",
      "cn-qingdao-cm9": "dm.aliyuncs.com",
      "cn-shanghai": "dm.aliyuncs.com",
      "cn-shanghai-et2-b01": "dm.aliyuncs.com",
      "cn-shanghai-inner": "dm.aliyuncs.com",
      "cn-shenzhen": "dm.aliyuncs.com",
      "cn-shenzhen-inner": "dm.aliyuncs.com",
      "us-east-1": "dm.aliyuncs.com",
      "us-west-1": "dm.aliyuncs.com"
    }
  }, {
    "name": "Green",
    "major_version": "2017-01-12",
    "domain": "green.aliyuncs.com,green.[RegionId].aliyuncs.com",
    "location_service_code": "green",
    "endpoints": {
      "ap-southeast-1": "green.aliyuncs.com",
      "cn-beijing": "green.aliyuncs.com",
      "cn-beijing-inner": "green.aliyuncs.com",
      "cn-hangzhou": "green.cn-hangzhou.aliyuncs.com",
      "cn-hangzhou-d": "green.aliyuncs.com",
      "cn-hongkong": "green.aliyuncs.com",
      "cn-qingdao": "green.aliyuncs.com",
      "cn-qingdao-cm9": "green.aliyuncs.com",
      "cn-shanghai": "green.cn-shanghai.aliyuncs.com",
      "cn-shanghai-et2-b01": "green.aliyuncs.com",
      "cn-shanghai-inner": "green.aliyuncs.com",
      "cn-shenzhen": "green.aliyuncs.com",
      "cn-shenzhen-inner": "green.aliyuncs.com",
      "us-east-1": "green.aliyuncs.com",
      "us-west-1": "green.aliyuncs.com"
    }
  }, {
    "name": "IdcCommonData",
    "major_version": "2017-06-28",
    "domain": "idc-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Pcdn",
    "major_version": "2017-04-11",
    "domain": "pcdn.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Agency",
    "major_version": "2016-08-01",
    "domain": "agency.aliyuncs.com,agency-inner.aliyuncs.com,agency-inner.[RegionId].aliyuncs.com,agency.[RegionId].aliyuncs.com,agency-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "BatchCompute",
    "major_version": "2015-11-11",
    "domain": "batchcompute.[RegionId].aliyuncs.com,batchcompute-vpc.[RegionId].aliyuncs.com",
    "location_service_code": "vpc",
    "endpoints": {
      "ap-southeast-1": "batchCompute.aliyuncs.com",
      "cn-beijing": "batchCompute.aliyuncs.com",
      "cn-hangzhou": "batchCompute.aliyuncs.com",
      "cn-hongkong": "batchCompute.aliyuncs.com",
      "cn-qingdao": "batchcompute.cn-qingdao.aliyuncs.com",
      "cn-shanghai": "batchCompute.aliyuncs.com",
      "cn-shanghai-et2-b01": "batchCompute.aliyuncs.com",
      "cn-shenzhen": "batchcompute.cn-shenzhen.aliyuncs.com",
      "us-east-1": "batchCompute.aliyuncs.com",
      "us-west-1": "batchCompute.aliyuncs.com"
    }
  }, {
    "name": "ChargingService",
    "major_version": "2016-12-19",
    "domain": "chargingservice.aliyuncs.com,chargingservice-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "chargingservice.aliyuncs.com",
      "cn-beijing": "chargingservice.aliyuncs.com",
      "cn-beijing-inner": "chargingservice.aliyuncs.com",
      "cn-hangzhou": "chargingservice.aliyuncs.com",
      "cn-hangzhou-d": "chargingservice.aliyuncs.com",
      "cn-hongkong": "chargingservice.aliyuncs.com",
      "cn-qingdao-cm9": "chargingservice.aliyuncs.com",
      "cn-shanghai": "chargingservice.aliyuncs.com",
      "cn-shanghai-et2-b01": "chargingservice.aliyuncs.com",
      "cn-shanghai-inner": "chargingservice.aliyuncs.com",
      "cn-shenzhen-inner": "chargingservice.aliyuncs.com",
      "us-east-1": "chargingservice.aliyuncs.com",
      "us-west-1": "chargingservice.aliyuncs.com"
    }
  }, {
    "name": "Promotion",
    "major_version": "2016-12-20",
    "domain": "promotion-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "datav",
    "major_version": "2017-11-22",
    "domain": "datav-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Yundunxianzhi",
    "major_version": "2017-06-06",
    "domain": "yundunxianzhi-share.aliyuncs.com,yundunxianzhi.aliyuncs.com,yundunxianzhi.[RegionId].aliyuncs.com",
    "location_service_code": "xianzhi",
    "endpoints": {}
  }, {
    "name": "yundun-high-vpc",
    "major_version": "2016-04-18",
    "domain": "yundun-high-inner.cn-hongkong.aliyuncs.com,yundun-high-share.cn-hongkong.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Chatbot",
    "major_version": "2017-10-11",
    "domain": "chatbot.[RegionId].aliyuncs.com",
    "location_service_code": "beebot",
    "endpoints": {}
  }, {
    "name": "Dycdpapi",
    "major_version": "2017-05-25",
    "domain": "dycdpapi.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "ErrorCenter",
    "major_version": "2017-09-01",
    "domain": "errorcenter.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Actiontrail",
    "major_version": "2015-09-28",
    "domain": "actiontrail.[RegionId].aliyuncs.com,actiontrail-inner.[RegionId].aliyuncs.com,actiontrail.aliyuncs.com",
    "location_service_code": "actiontrail",
    "endpoints": {}
  }, {
    "name": "Billing",
    "major_version": "2016-12-08",
    "domain": "billing.aliyuncs.com,billing-share.aliyuncs.com,billing-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "billing.aliyuncs.com",
      "cn-beijing": "billing.aliyuncs.com",
      "cn-beijing-inner": "billing.aliyuncs.com",
      "cn-hangzhou": "billing.aliyuncs.com",
      "cn-hangzhou-d": "billing.aliyuncs.com",
      "cn-hongkong": "billing.aliyuncs.com",
      "cn-qingdao-cm9": "billing.aliyuncs.com",
      "cn-shanghai": "billing.aliyuncs.com",
      "cn-shanghai-et2-b01": "billing.aliyuncs.com",
      "cn-shanghai-inner": "billing.aliyuncs.com",
      "cn-shenzhen-inner": "billing.aliyuncs.com",
      "us-east-1": "billing.aliyuncs.com",
      "us-west-1": "billing.aliyuncs.com"
    }
  }, {
    "name": "Yundunoem-partner",
    "major_version": "2017-04-21",
    "domain": "yundunoem.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Workorder",
    "major_version": "2016-08-30",
    "domain": "workorder.aliyuncs.com,workorder-share.aliyuncs.com,workorder.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "workorder.aliyuncs.com",
      "cn-beijing": "workorder.aliyuncs.com",
      "cn-beijing-inner": "workorder.aliyuncs.com",
      "cn-hangzhou": "workorder.aliyuncs.com",
      "cn-hangzhou-d": "workorder.aliyuncs.com",
      "cn-hongkong": "workorder.aliyuncs.com",
      "cn-qingdao-cm9": "workorder.aliyuncs.com",
      "cn-shanghai": "workorder.aliyuncs.com",
      "cn-shanghai-et2-b01": "workorder.aliyuncs.com",
      "cn-shanghai-inner": "workorder.aliyuncs.com",
      "cn-shenzhen-inner": "workorder.aliyuncs.com",
      "us-east-1": "workorder.aliyuncs.com",
      "us-west-1": "workorder.aliyuncs.com"
    }
  }, {
    "name": "Billingservice-inner",
    "major_version": "2016-08-18",
    "domain": "billingservice-inner.aliyuncs.com,resourcepack-share.aliyuncs.com,resourcepack-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Cdn",
    "major_version": "2014-11-11",
    "domain": "cdn-pop.aliyuncs.com,cdn.aliyuncs.com,cdn-inner.aliyuncs.com,cdn-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "cdn.aliyuncs.com",
      "cn-beijing": "cdn.aliyuncs.com",
      "cn-beijing-inner": "cdn.aliyuncs.com",
      "cn-hangzhou": "cdn.aliyuncs.com",
      "cn-hangzhou-d": "cdn.aliyuncs.com",
      "cn-hongkong": "cdn.aliyuncs.com",
      "cn-qingdao": "cdn.aliyuncs.com",
      "cn-qingdao-cm9": "cdn.aliyuncs.com",
      "cn-shanghai": "cdn.aliyuncs.com",
      "cn-shanghai-et2-b01": "cdn.aliyuncs.com",
      "cn-shanghai-inner": "cdn.aliyuncs.com",
      "cn-shenzhen": "cdn.aliyuncs.com",
      "cn-shenzhen-inner": "cdn.aliyuncs.com",
      "us-east-1": "cdn.aliyuncs.com",
      "us-west-1": "cdn.aliyuncs.com"
    }
  }, {
    "name": "Rs",
    "major_version": "2015-10-26",
    "domain": "rs.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Cbn-inner",
    "major_version": "2017-09-12",
    "domain": "cbn-inner.aliyuncs.com,cbn-inner.[RegionId].aliyuncs.com,cbn-share.[RegionId].aliyuncs.com,cbn-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Chiji-Inner",
    "major_version": "2016-03-30",
    "domain": "chiji-inner.aliyuncs.com,chiji-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "connect",
    "major_version": "2017-06-25",
    "domain": "connect.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "cn-hangzhou": "connect.aliyuncs.com"
    }
  }, {
    "name": "drcloud",
    "major_version": "2017-08-24",
    "domain": "drcloud.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Drds",
    "major_version": "2015-04-13",
    "domain": "drds.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "drds.aliyuncs.com",
      "cn-beijing": "drds.aliyuncs.com",
      "cn-beijing-inner": "drds.aliyuncs.com",
      "cn-hangzhou": "drds.aliyuncs.com",
      "cn-hangzhou-d": "drds.aliyuncs.com",
      "cn-hongkong": "drds.aliyuncs.com",
      "cn-qingdao": "drds.aliyuncs.com",
      "cn-qingdao-cm9": "drds.aliyuncs.com",
      "cn-shanghai": "drds.aliyuncs.com",
      "cn-shanghai-et2-b01": "drds.aliyuncs.com",
      "cn-shanghai-inner": "drds.aliyuncs.com",
      "cn-shenzhen": "drds.aliyuncs.com",
      "cn-shenzhen-inner": "drds.aliyuncs.com",
      "us-east-1": "drds.aliyuncs.com",
      "us-west-1": "drds.aliyuncs.com"
    }
  }, {
    "name": "HelpService",
    "major_version": "2016-10-10",
    "domain": "helpservice-inner.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Sts",
    "major_version": "2015-04-01",
    "domain": "sts-openapi-daily.alibaba.net,sts.aliyuncs.com,sts-inner.aliyuncs.com,sts.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-northeast-1": "sts.ap-northeast-1.aliyuncs.com",
      "ap-southeast-1": "sts.aliyuncs.com",
      "cn-beijing": "sts.aliyuncs.com",
      "cn-beijing-inner": "sts.aliyuncs.com",
      "cn-hangzhou": "sts.aliyuncs.com",
      "cn-hangzhou-d": "sts.aliyuncs.com",
      "cn-hongkong": "sts.aliyuncs.com",
      "cn-qingdao": "sts.aliyuncs.com",
      "cn-qingdao-cm9": "sts.aliyuncs.com",
      "cn-shanghai": "sts.aliyuncs.com",
      "cn-shanghai-et2-b01": "sts.aliyuncs.com",
      "cn-shanghai-inner": "sts.aliyuncs.com",
      "cn-shenzhen": "sts.aliyuncs.com",
      "cn-shenzhen-inner": "sts.aliyuncs.com",
      "us-east-1": "sts.aliyuncs.com",
      "us-west-1": "sts.aliyuncs.com"
    }
  }, {
    "name": "IOT_CITY",
    "major_version": "2017-07-04",
    "domain": "iot-city.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "NAS",
    "major_version": "2016-02-29",
    "domain": "nasservice-inner.aliyuncs.com,nasservice.aliyuncs.com,nas.aliyuncs.com,nas.[RegionId].aliyuncs.com,nasservice-share.aliyuncs.com",
    "location_service_code": "nas",
    "endpoints": {}
  }, {
    "name": "OA",
    "major_version": "2017-03-08",
    "domain": "okapi.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "dataplus-public",
    "major_version": "2017-04-24",
    "domain": "dataplus.[RegionId].aliyuncs.com,dataplus-internet.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "dms",
    "major_version": "2017-12-19",
    "domain": "dms.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "xtee",
    "major_version": "2017-10-01",
    "domain": "riskcontrol.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "",
    "major_version": "",
    "domain": "",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Bsn",
    "major_version": "2015-05-12",
    "domain": "bsn.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "EdasFinance",
    "major_version": "2017-04-05",
    "domain": "edasfinance.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "publicopinion",
    "major_version": "2017-07-31",
    "domain": "publicopinion.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "waf-openapi",
    "major_version": "2017-09-30",
    "domain": "wafopenapi.cn-hangzhou.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Dds",
    "major_version": "2015-12-01",
    "domain": "mongodb.aliyuncs.com,mongodb.[RegionId].aliyuncs.com,mongodb-inner.aliyuncs.com,mongodb-share.aliyuncs.com,mongodb-share.[RegionId].aliyuncs.com",
    "location_service_code": "dds",
    "endpoints": {
      "ap-southeast-1": "mongodb.aliyuncs.com",
      "cn-beijing": "mongodb.aliyuncs.com",
      "cn-beijing-inner": "mongodb.aliyuncs.com",
      "cn-hangzhou": "mongodb.aliyuncs.com",
      "cn-hangzhou-d": "mongodb.aliyuncs.com",
      "cn-hongkong": "mongodb.aliyuncs.com",
      "cn-qingdao": "mongodb.aliyuncs.com",
      "cn-qingdao-cm9": "mongodb.aliyuncs.com",
      "cn-shanghai": "mongodb.aliyuncs.com",
      "cn-shanghai-et2-b01": "mongodb.aliyuncs.com",
      "cn-shanghai-inner": "mongodb.aliyuncs.com",
      "cn-shenzhen": "mongodb.aliyuncs.com",
      "cn-shenzhen-inner": "mongodb.aliyuncs.com",
      "us-east-1": "mongodb.aliyuncs.com",
      "us-west-1": "mongodb.aliyuncs.com"
    }
  }, {
    "name": "Grandcanal",
    "major_version": "2016-07-15",
    "domain": "grandcanal-inner.aliyuncs.com,grandcanal-inner.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "HPC",
    "major_version": "2016-12-13",
    "domain": "hpc.aliyuncs.com,hpc.[RegionId].aliyuncs.com",
    "location_service_code": "hpc",
    "endpoints": {
      "ap-southeast-1": "hpc.aliyuncs.com",
      "cn-beijing": "hpc.aliyuncs.com",
      "cn-beijing-inner": "hpc.aliyuncs.com",
      "cn-hangzhou": "hpc.aliyuncs.com",
      "cn-hangzhou-d": "hpc.aliyuncs.com",
      "cn-hongkong": "hpc.aliyuncs.com",
      "cn-qingdao": "hpc.aliyuncs.com",
      "cn-qingdao-cm9": "hpc.aliyuncs.com",
      "cn-shanghai": "hpc.aliyuncs.com",
      "cn-shanghai-et2-b01": "hpc.aliyuncs.com",
      "cn-shanghai-inner": "hpc.aliyuncs.com",
      "cn-shenzhen": "hpc.aliyuncs.com",
      "cn-shenzhen-inner": "hpc.aliyuncs.com",
      "us-east-1": "hpc.aliyuncs.com",
      "us-west-1": "hpc.aliyuncs.com"
    }
  }, {
    "name": "Location-inner",
    "major_version": "2015-12-25",
    "domain": "location-inner.aliyuncs.com,location-inner.[RegionId].aliyuncs.com,location-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "location-inner.aliyuncs.com",
      "cn-beijing": "location-inner.aliyuncs.com",
      "cn-beijing-inner": "location-inner.aliyuncs.com",
      "cn-hangzhou": "location-inner.aliyuncs.com",
      "cn-hangzhou-d": "location-inner.aliyuncs.com",
      "cn-hongkong": "location-inner.aliyuncs.com",
      "cn-qingdao": "location-inner.aliyuncs.com",
      "cn-qingdao-cm9": "location-inner.aliyuncs.com",
      "cn-shanghai": "location-inner.aliyuncs.com",
      "cn-shanghai-et2-b01": "location-inner.aliyuncs.com",
      "cn-shanghai-inner": "location-inner.aliyuncs.com",
      "cn-shenzhen": "location-inner.aliyuncs.com",
      "cn-shenzhen-inner": "location-inner.aliyuncs.com",
      "us-east-1": "location-inner.aliyuncs.com",
      "us-west-1": "location-inner.aliyuncs.com"
    }
  }, {
    "name": "Msc",
    "major_version": "2016-06-15",
    "domain": "msc-service-inner.aliyuncs.com,msc-inner.aliyuncs.com,msc.aliyuncs.com,msc-service.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "msc-inner.aliyuncs.com",
      "cn-beijing": "msc-inner.aliyuncs.com",
      "cn-beijing-inner": "msc-inner.aliyuncs.com",
      "cn-hangzhou": "msc-inner.aliyuncs.com",
      "cn-hangzhou-d": "msc-inner.aliyuncs.com",
      "cn-hongkong": "msc-inner.aliyuncs.com",
      "cn-qingdao-cm9": "msc-inner.aliyuncs.com",
      "cn-shanghai": "msc-inner.aliyuncs.com",
      "cn-shanghai-et2-b01": "msc-inner.aliyuncs.com",
      "cn-shanghai-inner": "msc-inner.aliyuncs.com",
      "cn-shenzhen-inner": "msc-inner.aliyuncs.com",
      "us-east-1": "msc-inner.aliyuncs.com",
      "us-west-1": "msc-inner.aliyuncs.com"
    }
  }, {
    "name": "Ots",
    "major_version": "2016-06-20",
    "domain": "ots.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "ots-pop.aliyuncs.com",
      "cn-beijing": "ots-pop.aliyuncs.com",
      "cn-beijing-inner": "ots-pop.aliyuncs.com",
      "cn-hangzhou": "ots-pop.aliyuncs.com",
      "cn-hangzhou-d": "ots-pop.aliyuncs.com",
      "cn-hongkong": "ots-pop.aliyuncs.com",
      "cn-qingdao": "ots-pop.aliyuncs.com",
      "cn-qingdao-cm9": "ots-pop.aliyuncs.com",
      "cn-shanghai": "ots-pop.aliyuncs.com",
      "cn-shanghai-et2-b01": "ots-pop.aliyuncs.com",
      "cn-shanghai-inner": "ots-pop.aliyuncs.com",
      "cn-shenzhen": "ots-pop.aliyuncs.com",
      "cn-shenzhen-inner": "ots-pop.aliyuncs.com",
      "us-east-1": "ots-pop.aliyuncs.com",
      "us-west-1": "ots-pop.aliyuncs.com"
    }
  }, {
    "name": "faas",
    "major_version": "2017-08-24",
    "domain": "faas.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "hdr",
    "major_version": "2017-09-25",
    "domain": "hdr.aliyuncs.com,hdr.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Ace-ops",
    "major_version": "2015-09-09",
    "domain": "ace-ops.cn-hangzhou.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "cn-beijing": "ace-ops.cn-hangzhou.aliyuncs.com",
      "cn-hangzhou": "ace-ops.cn-hangzhou.aliyuncs.com",
      "cn-hongkong": "ace-ops.cn-hangzhou.aliyuncs.com",
      "cn-qingdao": "ace-ops.cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "ace-ops.cn-hangzhou.aliyuncs.com",
      "cn-shanghai-et2-b01": "ace-ops.cn-hangzhou.aliyuncs.com",
      "cn-shenzhen": "ace-ops.cn-hangzhou.aliyuncs.com",
      "us-east-1": "ace-ops.cn-hangzhou.aliyuncs.com",
      "us-west-1": "ace-ops.cn-hangzhou.aliyuncs.com"
    }
  }, {
    "name": "EWS",
    "major_version": "2017-06-01",
    "domain": "ews.[RegionId].aliyuncs.com,ews-share.[RegionId].aliyuncs.com,ews-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Huodong",
    "major_version": "2017-05-25",
    "domain": "huodong.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "MarianaDataCenter",
    "major_version": "2017-09-01",
    "domain": "mariana-datacenter-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Mhub",
    "major_version": "2017-08-25",
    "domain": "mhub.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "live",
    "major_version": "2016-11-01",
    "domain": "live.aliyuncs.com,live.[RegionId].aliyuncs.com",
    "location_service_code": "live",
    "endpoints": {
      "ap-southeast-1": "live.aliyuncs.com",
      "cn-beijing": "live.aliyuncs.com",
      "cn-beijing-inner": "live.aliyuncs.com",
      "cn-hangzhou": "live.aliyuncs.com",
      "cn-hangzhou-d": "live.aliyuncs.com",
      "cn-hongkong": "live.aliyuncs.com",
      "cn-qingdao": "live.aliyuncs.com",
      "cn-qingdao-cm9": "live.aliyuncs.com",
      "cn-shanghai": "live.aliyuncs.com",
      "cn-shanghai-et2-b01": "live.aliyuncs.com",
      "cn-shanghai-inner": "live.aliyuncs.com",
      "cn-shenzhen": "live.aliyuncs.com",
      "cn-shenzhen-inner": "live.aliyuncs.com",
      "us-east-1": "live.aliyuncs.com",
      "us-west-1": "live.aliyuncs.com"
    }
  }, {
    "name": "ARMS4FINANCE",
    "major_version": "2017-11-30",
    "domain": "arms4finance.aliyuncs.com,arms4finance.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "DocHelpService",
    "major_version": "2016-11-11",
    "domain": "dochelp.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Hotfix",
    "major_version": "2017-01-18",
    "domain": "hotfix.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "cdisitecheck",
    "major_version": "2017-12-19",
    "domain": "cdisitecheck-inner.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Dyiot",
    "major_version": "2017-08-10",
    "domain": "dyiot.aliyuncs.com,dyiot.[RegionId].aliyuncs.com,dyiot-cn-shagnhai.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Intlservice",
    "major_version": "2017-04-20",
    "domain": "intl-inner.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Vpc-inner",
    "major_version": "2016-04-28",
    "domain": "vpc-inner.aliyuncs.com,vpc-inner.[RegionId].aliyuncs.com,vpc-share.[RegionId].aliyuncs.com,vpc-inner-mayi.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "cn-beijing": "vpc-inner.aliyuncs.com",
      "cn-hangzhou": "vpc-inner.aliyuncs.com",
      "cn-hongkong": "vpc-inner.aliyuncs.com",
      "cn-qingdao": "vpc-inner.aliyuncs.com",
      "cn-shanghai": "vpc-inner.aliyuncs.com",
      "cn-shanghai-et2-b01": "vpc-inner.aliyuncs.com",
      "cn-shenzhen": "vpc-inner.aliyuncs.com",
      "us-east-1": "vpc-inner.aliyuncs.com",
      "us-west-1": "vpc-inner.aliyuncs.com"
    }
  }, {
    "name": "Codestore",
    "major_version": "2017-06-06",
    "domain": "codestore-inner.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "LicenseService",
    "major_version": "2017-01-01",
    "domain": "license-inner.aliyuncs.com,license-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Crm",
    "major_version": "2015-04-08",
    "domain": "crm-cn-hangzhou.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "crm-cn-hangzhou.aliyuncs.com",
      "cn-beijing": "crm-cn-hangzhou.aliyuncs.com",
      "cn-beijing-inner": "crm-cn-hangzhou.aliyuncs.com",
      "cn-hangzhou": "crm-cn-hangzhou.aliyuncs.com",
      "cn-hangzhou-d": "crm-cn-hangzhou.aliyuncs.com",
      "cn-hongkong": "crm-cn-hangzhou.aliyuncs.com",
      "cn-qingdao": "crm-cn-hangzhou.aliyuncs.com",
      "cn-qingdao-cm9": "crm-cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "crm-cn-hangzhou.aliyuncs.com",
      "cn-shanghai-et2-b01": "crm-cn-hangzhou.aliyuncs.com",
      "cn-shanghai-inner": "crm-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen": "crm-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen-inner": "crm-cn-hangzhou.aliyuncs.com",
      "us-east-1": "crm-cn-hangzhou.aliyuncs.com",
      "us-west-1": "crm-cn-hangzhou.aliyuncs.com"
    }
  }, {
    "name": "Domain-intl",
    "major_version": "2017-12-18",
    "domain": "domain-intl.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "intlMarketProduct",
    "major_version": "2016-09-20",
    "domain": "intl-market-inner.aliyuncs.com,intl-market-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "CCC",
    "major_version": "2017-07-05",
    "domain": "ccc.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Dysms",
    "major_version": "2017-06-20",
    "domain": "dysms.aliyuncs.com,dysms.[RegionId].aliyuncs.com,dysms-cn-shagnhai.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Yundun",
    "major_version": "2015-04-16",
    "domain": "yundun-cn-hangzhou.aliyuncs.com,yundun-cn-hangzhou-inner.aliyuncs.com,yundun-in-west-antgroup-1.aliyuncs.com,yundun-in-west-antgroup-2.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "yundun-cn-hangzhou.aliyuncs.com",
      "cn-beijing": "yundun-cn-hangzhou.aliyuncs.com",
      "cn-beijing-inner": "yundun-cn-hangzhou.aliyuncs.com",
      "cn-hangzhou": "yundun-cn-hangzhou.aliyuncs.com",
      "cn-hangzhou-d": "yundun-cn-hangzhou.aliyuncs.com",
      "cn-hongkong": "yundun-cn-hangzhou.aliyuncs.com",
      "cn-qingdao": "yundun-cn-hangzhou.aliyuncs.com",
      "cn-qingdao-cm9": "yundun-cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "yundun-cn-hangzhou.aliyuncs.com",
      "cn-shanghai-et2-b01": "yundun-cn-hangzhou.aliyuncs.com",
      "cn-shanghai-inner": "yundun-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen": "yundun-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen-inner": "yundun-cn-hangzhou.aliyuncs.com",
      "us-east-1": "yundun-cn-hangzhou.aliyuncs.com",
      "us-west-1": "yundun-cn-hangzhou.aliyuncs.com"
    }
  }, {
    "name": "Phoenixsp-inner",
    "major_version": "2016-08-05",
    "domain": "phoenixsp-inner.aliyuncs.com,phoenixsp-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Sms",
    "major_version": "2016-09-27",
    "domain": "sms.aliyuncs.com,sms.[RegionId].aliyuncs.com,sms-cn-shagnhai.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "sms.aliyuncs.com",
      "cn-beijing": "sms.aliyuncs.com",
      "cn-beijing-inner": "sms.aliyuncs.com",
      "cn-hangzhou": "sms.aliyuncs.com",
      "cn-hangzhou-d": "sms.aliyuncs.com",
      "cn-hongkong": "sms.aliyuncs.com",
      "cn-qingdao": "sms.aliyuncs.com",
      "cn-qingdao-cm9": "sms.aliyuncs.com",
      "cn-shanghai": "sms.aliyuncs.com",
      "cn-shanghai-et2-b01": "sms.aliyuncs.com",
      "cn-shanghai-inner": "sms.aliyuncs.com",
      "cn-shenzhen": "sms.aliyuncs.com",
      "cn-shenzhen-inner": "sms.aliyuncs.com",
      "us-east-1": "sms.aliyuncs.com",
      "us-west-1": "sms.aliyuncs.com"
    }
  }, {
    "name": "Subscription",
    "major_version": "2016-06-28",
    "domain": "subscription-inner.aliyuncs.com,subscription-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "XinanData",
    "major_version": "2017-08-08",
    "domain": "idcisp-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "evidence",
    "major_version": "2017-09-15",
    "domain": "evidence.aliyuncs.com,cloud-evidence.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Alert",
    "major_version": "2015-08-15",
    "domain": "alert.aliyuncs.com,alert-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "alert.aliyuncs.com",
      "cn-beijing": "alert.aliyuncs.com",
      "cn-beijing-inner": "alert.aliyuncs.com",
      "cn-hangzhou": "alert.aliyuncs.com",
      "cn-hangzhou-d": "alert.aliyuncs.com",
      "cn-hongkong": "alert.aliyuncs.com",
      "cn-qingdao": "alert.aliyuncs.com",
      "cn-qingdao-cm9": "alert.aliyuncs.com",
      "cn-shanghai": "alert.aliyuncs.com",
      "cn-shanghai-et2-b01": "alert.aliyuncs.com",
      "cn-shanghai-inner": "alert.aliyuncs.com",
      "cn-shenzhen": "alert.aliyuncs.com",
      "cn-shenzhen-inner": "alert.aliyuncs.com",
      "us-east-1": "alert.aliyuncs.com",
      "us-west-1": "alert.aliyuncs.com"
    }
  }, {
    "name": "Alidns",
    "major_version": "2015-01-09",
    "domain": "alidns.aliyuncs.com,alidns-share.aliyuncs.com,dns.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "alidns.aliyuncs.com",
      "cn-beijing": "alidns.aliyuncs.com",
      "cn-beijing-inner": "alidns.aliyuncs.com",
      "cn-hangzhou": "alidns.aliyuncs.com",
      "cn-hangzhou-d": "alidns.aliyuncs.com",
      "cn-hongkong": "alidns.aliyuncs.com",
      "cn-qingdao": "alidns.aliyuncs.com",
      "cn-qingdao-cm9": "alidns.aliyuncs.com",
      "cn-shanghai": "alidns.aliyuncs.com",
      "cn-shanghai-et2-b01": "alidns.aliyuncs.com",
      "cn-shanghai-inner": "alidns.aliyuncs.com",
      "cn-shenzhen": "alidns.aliyuncs.com",
      "cn-shenzhen-inner": "alidns.aliyuncs.com",
      "us-east-1": "alidns.aliyuncs.com",
      "us-west-1": "alidns.aliyuncs.com"
    }
  }, {
    "name": "Dybaseapi",
    "major_version": "2017-05-25",
    "domain": "dybaseapi.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "PetaData",
    "major_version": "2016-01-01",
    "domain": "petadata.aliyuncs.com,petadata.[RegionId].aliyuncs.com,petadata-share.[RegionId].aliyuncs.com",
    "location_service_code": "petadata",
    "endpoints": {}
  }, {
    "name": "R-kvstore",
    "major_version": "2015-01-01",
    "domain": "r-kvstore-cn-hangzhou.aliyuncs.com,r-kvstore.aliyuncs.com,r-kvstore.[RegionId].aliyuncs.com,r-kvstore-cn-hangzhou-inner.aliyuncs.com,r-kvstore-in-west-antgroup-1.aliyuncs.com,r-kvstore-share.aliyuncs.com,r-kvstore-share.[RegionId].aliyuncs.com",
    "location_service_code": "kvstore",
    "endpoints": {
      "ap-southeast-1": "r-kvstore-cn-hangzhou.aliyuncs.com",
      "cn-beijing": "r-kvstore-cn-hangzhou.aliyuncs.com",
      "cn-beijing-inner": "r-kvstore-cn-hangzhou.aliyuncs.com",
      "cn-hangzhou": "r-kvstore-cn-hangzhou.aliyuncs.com",
      "cn-hangzhou-d": "r-kvstore-cn-hangzhou.aliyuncs.com",
      "cn-hongkong": "r-kvstore-cn-hangzhou.aliyuncs.com",
      "cn-qingdao": "r-kvstore-cn-hangzhou.aliyuncs.com",
      "cn-qingdao-cm9": "r-kvstore-cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "r-kvstore-cn-hangzhou.aliyuncs.com",
      "cn-shanghai-et2-b01": "r-kvstore-cn-hangzhou.aliyuncs.com",
      "cn-shanghai-inner": "r-kvstore-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen": "r-kvstore-cn-hangzhou.aliyuncs.com",
      "cn-shenzhen-inner": "r-kvstore-cn-hangzhou.aliyuncs.com",
      "us-east-1": "r-kvstore-cn-hangzhou.aliyuncs.com",
      "us-west-1": "r-kvstore-cn-hangzhou.aliyuncs.com"
    }
  }, {
    "name": "Sls",
    "major_version": "2016-08-01",
    "domain": "sls.aliyuncs.com,sls-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Cms",
    "major_version": "2017-03-01",
    "domain": "metrics.aliyuncs.com,metrics.[RegionId].aliyuncs.com,metrics-share.aliyuncs.com,metrics-share.[RegionId].aliyuncs.com",
    "location_service_code": "cms",
    "endpoints": {
      "ap-northeast-1": "metrics.ap-northeast-1.aliyuncs.com",
      "ap-southeast-1": "metrics.cn-hangzhou.aliyuncs.com",
      "ap-southeast-2": "metrics.cn-hangzhou.aliyuncs.com",
      "cn-beijing": "metrics.cn-hangzhou.aliyuncs.com",
      "cn-beijing-inner": "metrics.aliyuncs.com",
      "cn-hangzhou": "metrics.cn-hangzhou.aliyuncs.com",
      "cn-hangzhou-d": "metrics.aliyuncs.com",
      "cn-hongkong": "metrics.cn-hangzhou.aliyuncs.com",
      "cn-qingdao": "metrics.cn-hangzhou.aliyuncs.com",
      "cn-qingdao-cm9": "metrics.aliyuncs.com",
      "cn-shanghai": "metrics.cn-hangzhou.aliyuncs.com",
      "cn-shanghai-et2-b01": "metrics.aliyuncs.com",
      "cn-shanghai-inner": "metrics.aliyuncs.com",
      "cn-shenzhen": "metrics.cn-hangzhou.aliyuncs.com",
      "cn-shenzhen-inner": "metrics.aliyuncs.com",
      "cn-zhangjiakou": "metrics.cn-hangzhou.aliyuncs.com",
      "eu-central-1": "metrics.cn-hangzhou.aliyuncs.com",
      "me-east-1": "metrics.cn-hangzhou.aliyuncs.com",
      "us-east-1": "metrics.cn-hangzhou.aliyuncs.com",
      "us-west-1": "metrics.cn-hangzhou.aliyuncs.com"
    }
  }, {
    "name": "OpenAccount",
    "major_version": "2017-03-27",
    "domain": "openaccount.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "PTS-inner",
    "major_version": "2015-08-01",
    "domain": "pts-inner.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Market",
    "major_version": "2015-11-01",
    "domain": "market.aliyuncs.com,market.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Push",
    "major_version": "2016-08-01",
    "domain": "cloudpush.aliyuncs.com,cloudpush-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "cloudpush.aliyuncs.com",
      "cn-beijing": "cloudpush.aliyuncs.com",
      "cn-beijing-inner": "cloudpush.aliyuncs.com",
      "cn-hangzhou": "cloudpush.aliyuncs.com",
      "cn-hangzhou-d": "cloudpush.aliyuncs.com",
      "cn-hongkong": "cloudpush.aliyuncs.com",
      "cn-qingdao": "cloudpush.aliyuncs.com",
      "cn-qingdao-cm9": "cloudpush.aliyuncs.com",
      "cn-shanghai": "cloudpush.aliyuncs.com",
      "cn-shanghai-et2-b01": "cloudpush.aliyuncs.com",
      "cn-shanghai-inner": "cloudpush.aliyuncs.com",
      "cn-shenzhen": "cloudpush.aliyuncs.com",
      "cn-shenzhen-inner": "cloudpush.aliyuncs.com",
      "us-east-1": "cloudpush.aliyuncs.com",
      "us-west-1": "cloudpush.aliyuncs.com"
    }
  }, {
    "name": "R-kvstore-inner",
    "major_version": "2015-01-01",
    "domain": "r-kvstore-inner.aliyuncs.com,r-kvstore-inner.[RegionId].aliyuncs.com,r-kvstore-inc-share.aliyuncs.com,r-kvstore-inc-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "ak-openapi-pop",
    "major_version": "2016-07-14",
    "domain": "ak-inner.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "dingdingmarket",
    "major_version": "2017-12-30",
    "domain": "dingdingmarket-inner.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Commondriver",
    "major_version": "2016-04-28",
    "domain": "commondriver-inner.aliyuncs.com,commondriver-share.[RegionId].aliyuncs.com,commondriver-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "common.driver.aliyuncs.com",
      "cn-beijing": "common.driver.aliyuncs.com",
      "cn-beijing-inner": "common.driver.aliyuncs.com",
      "cn-hangzhou": "common.driver.aliyuncs.com",
      "cn-hangzhou-d": "common.driver.aliyuncs.com",
      "cn-hongkong": "common.driver.aliyuncs.com",
      "cn-qingdao": "common.driver.aliyuncs.com",
      "cn-qingdao-cm9": "common.driver.aliyuncs.com",
      "cn-shanghai": "common.driver.aliyuncs.com",
      "cn-shanghai-et2-b01": "common.driver.aliyuncs.com",
      "cn-shanghai-inner": "common.driver.aliyuncs.com",
      "cn-shenzhen": "common.driver.aliyuncs.com",
      "cn-shenzhen-inner": "common.driver.aliyuncs.com",
      "us-east-1": "common.driver.aliyuncs.com",
      "us-west-1": "common.driver.aliyuncs.com"
    }
  }, {
    "name": "Domain",
    "major_version": "2016-05-11",
    "domain": "domain.aliyuncs.com,domain-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "domain.aliyuncs.com",
      "cn-beijing": "domain.aliyuncs.com",
      "cn-beijing-inner": "domain.aliyuncs.com",
      "cn-hangzhou": "domain.aliyuncs.com",
      "cn-hangzhou-d": "domain.aliyuncs.com",
      "cn-hongkong": "domain.aliyuncs.com",
      "cn-qingdao": "domain.aliyuncs.com",
      "cn-qingdao-cm9": "domain.aliyuncs.com",
      "cn-shanghai": "domain.aliyuncs.com",
      "cn-shanghai-et2-b01": "domain.aliyuncs.com",
      "cn-shanghai-inner": "domain.aliyuncs.com",
      "cn-shenzhen": "domain.aliyuncs.com",
      "cn-shenzhen-inner": "domain.aliyuncs.com",
      "us-east-1": "domain.aliyuncs.com",
      "us-west-1": "domain.aliyuncs.com"
    }
  }, {
    "name": "EcsInc",
    "major_version": "2016-03-14",
    "domain": "ecs-inner.aliyuncs.com,ecs-inner.[RegionId].aliyuncs.com,ecs-api-inner.aliyuncs.com,ecs-api-inner.[RegionId].aliyuncs.com,ecs-api-share.[RegionId].aliyuncs.com,ecs-api-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "nls-cloud-meta",
    "major_version": "2017-12-14",
    "domain": "nls-meta.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "polardb",
    "major_version": "2017-08-01",
    "domain": "polardb.aliyuncs.com,polardb-inner.aliyuncs.com,polardb-share.aliyuncs.com,polardb.[RegionId].aliyuncs.com,polardb-inner.[RegionId].aliyuncs.com,polardb-share.[RegionId].aliyuncs.com",
    "location_service_code": "polardb",
    "endpoints": {}
  }, {
    "name": "Ram",
    "major_version": "2015-05-01",
    "domain": "ram.aliyuncs.com,ram-inner.aliyuncs.com,ram-in-west-antgroup-1.aliyuncs.com,ram-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-northeast-1": "ram.aliyuncs.com",
      "ap-southeast-1": "ram.aliyuncs.com",
      "cn-beijing": "ram.aliyuncs.com",
      "cn-beijing-inner": "ram.aliyuncs.com",
      "cn-hangzhou": "ram.aliyuncs.com",
      "cn-hangzhou-d": "ram.aliyuncs.com",
      "cn-hongkong": "ram.aliyuncs.com",
      "cn-qingdao": "ram.aliyuncs.com",
      "cn-qingdao-cm9": "ram.aliyuncs.com",
      "cn-shanghai": "ram.aliyuncs.com",
      "cn-shanghai-et2-b01": "ram.aliyuncs.com",
      "cn-shanghai-inner": "ram.aliyuncs.com",
      "cn-shenzhen": "ram.aliyuncs.com",
      "cn-shenzhen-inner": "ram.aliyuncs.com",
      "us-east-1": "ram.aliyuncs.com",
      "us-west-1": "ram.aliyuncs.com"
    }
  }, {
    "name": "ResourceManager",
    "major_version": "2016-11-11",
    "domain": "resourcemanager.aliyuncs.com,resourcemanager-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Sas-api",
    "major_version": "2017-07-05",
    "domain": "sas-api.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Points",
    "major_version": "2017-05-08",
    "domain": "points.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "YqBridge",
    "major_version": "2017-08-10",
    "domain": "yq-bridge.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Yundunhsm",
    "major_version": "2016-04-10",
    "domain": "yundunhsm.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "yundunhsm.aliyuncs.com",
      "cn-beijing": "yundunhsm.aliyuncs.com",
      "cn-beijing-inner": "yundunhsm.aliyuncs.com",
      "cn-hangzhou": "yundunhsm.aliyuncs.com",
      "cn-hangzhou-d": "yundunhsm.aliyuncs.com",
      "cn-hongkong": "yundunhsm.aliyuncs.com",
      "cn-qingdao-cm9": "yundunhsm.aliyuncs.com",
      "cn-shanghai": "yundunhsm.aliyuncs.com",
      "cn-shanghai-et2-b01": "yundunhsm.aliyuncs.com",
      "cn-shanghai-inner": "yundunhsm.aliyuncs.com",
      "cn-shenzhen-inner": "yundunhsm.aliyuncs.com",
      "us-east-1": "yundunhsm.aliyuncs.com",
      "us-west-1": "yundunhsm.aliyuncs.com"
    }
  }, {
    "name": "antiddos",
    "major_version": "2016-07-12",
    "domain": "antiddos-inner.cn-hangzhou.aliyuncs.com,antiddos-share.[RegionId].aliyuncs.com,antiddos-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "hitsdb",
    "major_version": "2017-06-01",
    "domain": "hitsdb.aliyuncs.com,hitsdb.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "vod",
    "major_version": "2017-03-21",
    "domain": "vod.aliyuncs.com,vod.[RegionId].aliyuncs.com",
    "location_service_code": "vod",
    "endpoints": {
      "cn-beijing": "vod.cn-beijing.aliyuncs.com",
      "cn-shanghai": "vod.cn-shanghai.aliyuncs.com"
    }
  }, {
    "name": "yundun-high",
    "major_version": "2017-07-25",
    "domain": "yundun-high-internal.aliyuncs.com,yundun-high-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Beebot-inner",
    "major_version": "2017-08-21",
    "domain": "beebot-inner.aliyuncs.com,beebot-inner.[RegionId].aliyuncs.com,beebot-inner-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Dyvmsapi",
    "major_version": "2017-05-25",
    "domain": "dyvmsapi.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "OssAdmin",
    "major_version": "2017-01-15",
    "domain": "oss-admin.aliyuncs.com,oss-admin-taiwan.aliyuncs.com,oss-in-west-antgroup-1.aliyuncs.com,oss-in-west-antgroup-2.aliyuncs.com,oss-admin-share.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "oss-admin.aliyuncs.com",
      "cn-beijing": "oss-admin.aliyuncs.com",
      "cn-beijing-inner": "oss-admin.aliyuncs.com",
      "cn-hangzhou": "oss-admin.aliyuncs.com",
      "cn-hangzhou-d": "oss-admin.aliyuncs.com",
      "cn-hongkong": "oss-admin.aliyuncs.com",
      "cn-qingdao": "oss-admin.aliyuncs.com",
      "cn-qingdao-cm9": "oss-admin.aliyuncs.com",
      "cn-shanghai": "oss-admin.aliyuncs.com",
      "cn-shanghai-et2-b01": "oss-admin.aliyuncs.com",
      "cn-shanghai-inner": "oss-admin.aliyuncs.com",
      "cn-shenzhen": "oss-admin.aliyuncs.com",
      "cn-shenzhen-inner": "oss-admin.aliyuncs.com",
      "us-east-1": "oss-admin.aliyuncs.com",
      "us-west-1": "oss-admin.aliyuncs.com"
    }
  }, {
    "name": "scdn",
    "major_version": "2017-11-15",
    "domain": "scdn.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "yundun-sos-service",
    "major_version": "2016-05-13",
    "domain": "yundun-sos-service-internal.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "payment-service",
    "major_version": "2017-01-18",
    "domain": "payment-service.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Ecsops",
    "major_version": "2016-04-01",
    "domain": "ecsops-inner.aliyuncs.com,ecsops-inner.[RegionId].aliyuncs.com,ecsops-share.aliyuncs.com,ecsops-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Mqc",
    "major_version": "2017-02-23",
    "domain": "mqc-inner.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "hbr",
    "major_version": "2017-09-08",
    "domain": "hbr.aliyuncs.com,hbr.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "dataplus-measure",
    "major_version": "2017-09-29",
    "domain": "dataplus-measure.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "gpdbForInner",
    "major_version": "2016-05-03",
    "domain": "gpdb-inner.aliyuncs.com,gpdb-inner.[RegionId].aliyuncs.com,gpdb-inc-share.aliyuncs.com,gpdb-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Dysmsapi",
    "major_version": "2017-05-25",
    "domain": "dysmsapi.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Sas",
    "major_version": "2017-07-13",
    "domain": "sas.aliyuncs.com,tbzx.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "cr",
    "major_version": "2016-06-07",
    "domain": "cr.aliyuncs.com,cr.[RegionId].aliyuncs.com,cr-inner.[RegionId].aliyuncs.com,cr-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "gameshield-inner",
    "major_version": "2017-03-08",
    "domain": "gameshield-share.aliyuncs.com,gameshield-inner.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Acs",
    "major_version": "2015-01-01",
    "domain": "acs.aliyun-inc.com,acs.[RegionId].aliyun-inc.com",
    "location_service_code": "",
    "endpoints": {
      "cn-beijing": "acs.aliyun-inc.com",
      "cn-hangzhou": "acs.aliyun-inc.com",
      "cn-hongkong": "acs.aliyun-inc.com",
      "cn-qingdao": "acs.aliyun-inc.com",
      "cn-shanghai": "acs.aliyun-inc.com",
      "cn-shanghai-et2-b01": "acs.aliyun-inc.com",
      "cn-shenzhen": "acs.aliyun-inc.com",
      "us-east-1": "acs.aliyun-inc.com",
      "us-west-1": "acs.aliyun-inc.com"
    }
  }, {
    "name": "CF",
    "major_version": "2015-11-27",
    "domain": "cf.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {
      "ap-southeast-1": "cf.aliyuncs.com",
      "cn-beijing": "cf.aliyuncs.com",
      "cn-beijing-inner": "cf.aliyuncs.com",
      "cn-hangzhou": "cf.aliyuncs.com",
      "cn-hangzhou-d": "cf.aliyuncs.com",
      "cn-hongkong": "cf.aliyuncs.com",
      "cn-qingdao": "cf.aliyuncs.com",
      "cn-qingdao-cm9": "cf.aliyuncs.com",
      "cn-shanghai": "cf.aliyuncs.com",
      "cn-shanghai-et2-b01": "cf.aliyuncs.com",
      "cn-shanghai-inner": "cf.aliyuncs.com",
      "cn-shenzhen": "cf.aliyuncs.com",
      "cn-shenzhen-inner": "cf.aliyuncs.com",
      "us-east-1": "cf.aliyuncs.com",
      "us-west-1": "cf.aliyuncs.com"
    }
  }, {
    "name": "Market-Inner",
    "major_version": "2016-08-01",
    "domain": "market-inner.aliyuncs.com,market-share.aliyuncs.com,market-share.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "base-biz-baseapi",
    "major_version": "2016-11-11",
    "domain": "baseapi.aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "dataplus",
    "major_version": "2016-07-07",
    "domain": "dataplus-inner.aliyuncs.com,dataplus-share.aliyuncs.com,dataplus-inner.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Dbs-inner",
    "major_version": "2017-10-09",
    "domain": "dbs.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "ID2",
    "major_version": "2017-07-07",
    "domain": "id2.aliyuncs.com,id2.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }, {
    "name": "Slaapi",
    "major_version": "2017-01-12",
    "domain": "slaapi-inner.aliyuncs.com,slaapi-inner.[RegionId].aliyuncs.com",
    "location_service_code": "",
    "endpoints": {}
  }]
}
`)