// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: aliyun_openapi_meta.proto

package pbmeta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandDefinition is the stable, API-agnostic metadata schema interpreted by
// common-runtime. It describes an operation; it does not generate one Go type
// per Alibaba Cloud API.
type CommandDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductCode   string                 `protobuf:"bytes,1,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CmdName       string                 `protobuf:"bytes,3,opt,name=cmd_name,json=cmdName,proto3" json:"cmd_name,omitempty"`
	CmdFullName   string                 `protobuf:"bytes,4,opt,name=cmd_full_name,json=cmdFullName,proto3" json:"cmd_full_name,omitempty"`
	DescriptionZh string                 `protobuf:"bytes,5,opt,name=description_zh,json=descriptionZh,proto3" json:"description_zh,omitempty"`
	DescriptionEn string                 `protobuf:"bytes,6,opt,name=description_en,json=descriptionEn,proto3" json:"description_en,omitempty"`
	Method        string                 `protobuf:"bytes,7,opt,name=method,proto3" json:"method,omitempty"`
	MultiVersion  bool                   `protobuf:"varint,8,opt,name=multi_version,json=multiVersion,proto3" json:"multi_version,omitempty"`
	Deprecated    bool                   `protobuf:"varint,9,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	KebabExample  string                 `protobuf:"bytes,10,opt,name=kebab_example,json=kebabExample,proto3" json:"kebab_example,omitempty"`
	CamelExample  string                 `protobuf:"bytes,11,opt,name=camel_example,json=camelExample,proto3" json:"camel_example,omitempty"`
	Operation     *Operation             `protobuf:"bytes,12,opt,name=operation,proto3" json:"operation,omitempty"`
	Parameters    []*Argument            `protobuf:"bytes,13,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandDefinition) Reset() {
	*x = CommandDefinition{}
	mi := &file_aliyun_openapi_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDefinition) ProtoMessage() {}

func (x *CommandDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_aliyun_openapi_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDefinition.ProtoReflect.Descriptor instead.
func (*CommandDefinition) Descriptor() ([]byte, []int) {
	return file_aliyun_openapi_meta_proto_rawDescGZIP(), []int{0}
}

func (x *CommandDefinition) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *CommandDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandDefinition) GetCmdName() string {
	if x != nil {
		return x.CmdName
	}
	return ""
}

func (x *CommandDefinition) GetCmdFullName() string {
	if x != nil {
		return x.CmdFullName
	}
	return ""
}

func (x *CommandDefinition) GetDescriptionZh() string {
	if x != nil {
		return x.DescriptionZh
	}
	return ""
}

func (x *CommandDefinition) GetDescriptionEn() string {
	if x != nil {
		return x.DescriptionEn
	}
	return ""
}

func (x *CommandDefinition) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CommandDefinition) GetMultiVersion() bool {
	if x != nil {
		return x.MultiVersion
	}
	return false
}

func (x *CommandDefinition) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *CommandDefinition) GetKebabExample() string {
	if x != nil {
		return x.KebabExample
	}
	return ""
}

func (x *CommandDefinition) GetCamelExample() string {
	if x != nil {
		return x.CamelExample
	}
	return ""
}

func (x *CommandDefinition) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *CommandDefinition) GetParameters() []*Argument {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Operation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Action          string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	ApiStyle        string                 `protobuf:"bytes,2,opt,name=api_style,json=apiStyle,proto3" json:"api_style,omitempty"`
	ApiVersion      string                 `protobuf:"bytes,3,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Method          string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Protocol        string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Url             string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	IsSse           bool                   `protobuf:"varint,7,opt,name=is_sse,json=isSse,proto3" json:"is_sse,omitempty"`
	ReqBodyType     string                 `protobuf:"bytes,8,opt,name=req_body_type,json=reqBodyType,proto3" json:"req_body_type,omitempty"`
	ContentType     string                 `protobuf:"bytes,9,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	HasWildcardPath bool                   `protobuf:"varint,10,opt,name=has_wildcard_path,json=hasWildcardPath,proto3" json:"has_wildcard_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_aliyun_openapi_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_aliyun_openapi_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_aliyun_openapi_meta_proto_rawDescGZIP(), []int{1}
}

func (x *Operation) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Operation) GetApiStyle() string {
	if x != nil {
		return x.ApiStyle
	}
	return ""
}

func (x *Operation) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Operation) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Operation) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Operation) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Operation) GetIsSse() bool {
	if x != nil {
		return x.IsSse
	}
	return false
}

func (x *Operation) GetReqBodyType() string {
	if x != nil {
		return x.ReqBodyType
	}
	return ""
}

func (x *Operation) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Operation) GetHasWildcardPath() bool {
	if x != nil {
		return x.HasWildcardPath
	}
	return false
}

type Argument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RawName       string                 `protobuf:"bytes,2,opt,name=raw_name,json=rawName,proto3" json:"raw_name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	HelpZh        string                 `protobuf:"bytes,5,opt,name=help_zh,json=helpZh,proto3" json:"help_zh,omitempty"`
	HelpEn        string                 `protobuf:"bytes,6,opt,name=help_en,json=helpEn,proto3" json:"help_en,omitempty"`
	Required      bool                   `protobuf:"varint,7,opt,name=required,proto3" json:"required,omitempty"`
	Location      string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	ParamStyle    string                 `protobuf:"bytes,9,opt,name=param_style,json=paramStyle,proto3" json:"param_style,omitempty"`
	Fields        []*Argument            `protobuf:"bytes,10,rep,name=fields,proto3" json:"fields,omitempty"`
	Element       *TypeShape             `protobuf:"bytes,11,opt,name=element,proto3" json:"element,omitempty"`
	Value         *TypeShape             `protobuf:"bytes,12,opt,name=value,proto3" json:"value,omitempty"`
	Example       string                 `protobuf:"bytes,13,opt,name=example,proto3" json:"example,omitempty"`
	IsWildcard    bool                   `protobuf:"varint,14,opt,name=is_wildcard,json=isWildcard,proto3" json:"is_wildcard,omitempty"`
	Enum          []string               `protobuf:"bytes,15,rep,name=enum,proto3" json:"enum,omitempty"`
	Minimum       string                 `protobuf:"bytes,16,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Maximum       string                 `protobuf:"bytes,17,opt,name=maximum,proto3" json:"maximum,omitempty"`
	Pattern       string                 `protobuf:"bytes,18,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Format        string                 `protobuf:"bytes,19,opt,name=format,proto3" json:"format,omitempty"`
	MinLength     string                 `protobuf:"bytes,20,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	MaxLength     string                 `protobuf:"bytes,21,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	DocRequired   bool                   `protobuf:"varint,22,opt,name=doc_required,json=docRequired,proto3" json:"doc_required,omitempty"`
	DirectBody    bool                   `protobuf:"varint,23,opt,name=direct_body,json=directBody,proto3" json:"direct_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Argument) Reset() {
	*x = Argument{}
	mi := &file_aliyun_openapi_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Argument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Argument) ProtoMessage() {}

func (x *Argument) ProtoReflect() protoreflect.Message {
	mi := &file_aliyun_openapi_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Argument.ProtoReflect.Descriptor instead.
func (*Argument) Descriptor() ([]byte, []int) {
	return file_aliyun_openapi_meta_proto_rawDescGZIP(), []int{2}
}

func (x *Argument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Argument) GetRawName() string {
	if x != nil {
		return x.RawName
	}
	return ""
}

func (x *Argument) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Argument) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Argument) GetHelpZh() string {
	if x != nil {
		return x.HelpZh
	}
	return ""
}

func (x *Argument) GetHelpEn() string {
	if x != nil {
		return x.HelpEn
	}
	return ""
}

func (x *Argument) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Argument) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Argument) GetParamStyle() string {
	if x != nil {
		return x.ParamStyle
	}
	return ""
}

func (x *Argument) GetFields() []*Argument {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Argument) GetElement() *TypeShape {
	if x != nil {
		return x.Element
	}
	return nil
}

func (x *Argument) GetValue() *TypeShape {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Argument) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *Argument) GetIsWildcard() bool {
	if x != nil {
		return x.IsWildcard
	}
	return false
}

func (x *Argument) GetEnum() []string {
	if x != nil {
		return x.Enum
	}
	return nil
}

func (x *Argument) GetMinimum() string {
	if x != nil {
		return x.Minimum
	}
	return ""
}

func (x *Argument) GetMaximum() string {
	if x != nil {
		return x.Maximum
	}
	return ""
}

func (x *Argument) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Argument) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Argument) GetMinLength() string {
	if x != nil {
		return x.MinLength
	}
	return ""
}

func (x *Argument) GetMaxLength() string {
	if x != nil {
		return x.MaxLength
	}
	return ""
}

func (x *Argument) GetDocRequired() bool {
	if x != nil {
		return x.DocRequired
	}
	return false
}

func (x *Argument) GetDirectBody() bool {
	if x != nil {
		return x.DirectBody
	}
	return false
}

// TypeShape is a depth-independent recursive description of a container
// child. Arrays use element and maps use value at every level.
type TypeShape struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Fields        []*Argument            `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Element       *TypeShape             `protobuf:"bytes,3,opt,name=element,proto3" json:"element,omitempty"`
	Value         *TypeShape             `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Enum          []string               `protobuf:"bytes,5,rep,name=enum,proto3" json:"enum,omitempty"`
	Minimum       string                 `protobuf:"bytes,6,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Maximum       string                 `protobuf:"bytes,7,opt,name=maximum,proto3" json:"maximum,omitempty"`
	Pattern       string                 `protobuf:"bytes,8,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Format        string                 `protobuf:"bytes,9,opt,name=format,proto3" json:"format,omitempty"`
	MinLength     string                 `protobuf:"bytes,10,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	MaxLength     string                 `protobuf:"bytes,11,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeShape) Reset() {
	*x = TypeShape{}
	mi := &file_aliyun_openapi_meta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeShape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeShape) ProtoMessage() {}

func (x *TypeShape) ProtoReflect() protoreflect.Message {
	mi := &file_aliyun_openapi_meta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeShape.ProtoReflect.Descriptor instead.
func (*TypeShape) Descriptor() ([]byte, []int) {
	return file_aliyun_openapi_meta_proto_rawDescGZIP(), []int{3}
}

func (x *TypeShape) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TypeShape) GetFields() []*Argument {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *TypeShape) GetElement() *TypeShape {
	if x != nil {
		return x.Element
	}
	return nil
}

func (x *TypeShape) GetValue() *TypeShape {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TypeShape) GetEnum() []string {
	if x != nil {
		return x.Enum
	}
	return nil
}

func (x *TypeShape) GetMinimum() string {
	if x != nil {
		return x.Minimum
	}
	return ""
}

func (x *TypeShape) GetMaximum() string {
	if x != nil {
		return x.Maximum
	}
	return ""
}

func (x *TypeShape) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *TypeShape) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *TypeShape) GetMinLength() string {
	if x != nil {
		return x.MinLength
	}
	return ""
}

func (x *TypeShape) GetMaxLength() string {
	if x != nil {
		return x.MaxLength
	}
	return ""
}

var File_aliyun_openapi_meta_proto protoreflect.FileDescriptor

const file_aliyun_openapi_meta_proto_rawDesc = "" +
	"\n" +
	"\x19aliyun_openapi_meta.proto\x12\x16aliyun.openapi.meta.v1\"\x81\x04\n" +
	"\x11CommandDefinition\x12!\n" +
	"\fproduct_code\x18\x01 \x01(\tR\vproductCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bcmd_name\x18\x03 \x01(\tR\acmdName\x12\"\n" +
	"\rcmd_full_name\x18\x04 \x01(\tR\vcmdFullName\x12%\n" +
	"\x0edescription_zh\x18\x05 \x01(\tR\rdescriptionZh\x12%\n" +
	"\x0edescription_en\x18\x06 \x01(\tR\rdescriptionEn\x12\x16\n" +
	"\x06method\x18\a \x01(\tR\x06method\x12#\n" +
	"\rmulti_version\x18\b \x01(\bR\fmultiVersion\x12\x1e\n" +
	"\n" +
	"deprecated\x18\t \x01(\bR\n" +
	"deprecated\x12#\n" +
	"\rkebab_example\x18\n" +
	" \x01(\tR\fkebabExample\x12#\n" +
	"\rcamel_example\x18\v \x01(\tR\fcamelExample\x12?\n" +
	"\toperation\x18\f \x01(\v2!.aliyun.openapi.meta.v1.OperationR\toperation\x12@\n" +
	"\n" +
	"parameters\x18\r \x03(\v2 .aliyun.openapi.meta.v1.ArgumentR\n" +
	"parameters\"\xb1\x02\n" +
	"\tOperation\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1b\n" +
	"\tapi_style\x18\x02 \x01(\tR\bapiStyle\x12\x1f\n" +
	"\vapi_version\x18\x03 \x01(\tR\n" +
	"apiVersion\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x15\n" +
	"\x06is_sse\x18\a \x01(\bR\x05isSse\x12\"\n" +
	"\rreq_body_type\x18\b \x01(\tR\vreqBodyType\x12!\n" +
	"\fcontent_type\x18\t \x01(\tR\vcontentType\x12*\n" +
	"\x11has_wildcard_path\x18\n" +
	" \x01(\bR\x0fhasWildcardPath\"\xd9\x05\n" +
	"\bArgument\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\braw_name\x18\x02 \x01(\tR\arawName\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\x12\x17\n" +
	"\ahelp_zh\x18\x05 \x01(\tR\x06helpZh\x12\x17\n" +
	"\ahelp_en\x18\x06 \x01(\tR\x06helpEn\x12\x1a\n" +
	"\brequired\x18\a \x01(\bR\brequired\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12\x1f\n" +
	"\vparam_style\x18\t \x01(\tR\n" +
	"paramStyle\x128\n" +
	"\x06fields\x18\n" +
	" \x03(\v2 .aliyun.openapi.meta.v1.ArgumentR\x06fields\x12;\n" +
	"\aelement\x18\v \x01(\v2!.aliyun.openapi.meta.v1.TypeShapeR\aelement\x127\n" +
	"\x05value\x18\f \x01(\v2!.aliyun.openapi.meta.v1.TypeShapeR\x05value\x12\x18\n" +
	"\aexample\x18\r \x01(\tR\aexample\x12\x1f\n" +
	"\vis_wildcard\x18\x0e \x01(\bR\n" +
	"isWildcard\x12\x12\n" +
	"\x04enum\x18\x0f \x03(\tR\x04enum\x12\x18\n" +
	"\aminimum\x18\x10 \x01(\tR\aminimum\x12\x18\n" +
	"\amaximum\x18\x11 \x01(\tR\amaximum\x12\x18\n" +
	"\apattern\x18\x12 \x01(\tR\apattern\x12\x16\n" +
	"\x06format\x18\x13 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"min_length\x18\x14 \x01(\tR\tminLength\x12\x1d\n" +
	"\n" +
	"max_length\x18\x15 \x01(\tR\tmaxLength\x12!\n" +
	"\fdoc_required\x18\x16 \x01(\bR\vdocRequired\x12\x1f\n" +
	"\vdirect_body\x18\x17 \x01(\bR\n" +
	"directBody\"\x87\x03\n" +
	"\tTypeShape\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x128\n" +
	"\x06fields\x18\x02 \x03(\v2 .aliyun.openapi.meta.v1.ArgumentR\x06fields\x12;\n" +
	"\aelement\x18\x03 \x01(\v2!.aliyun.openapi.meta.v1.TypeShapeR\aelement\x127\n" +
	"\x05value\x18\x04 \x01(\v2!.aliyun.openapi.meta.v1.TypeShapeR\x05value\x12\x12\n" +
	"\x04enum\x18\x05 \x03(\tR\x04enum\x12\x18\n" +
	"\aminimum\x18\x06 \x01(\tR\aminimum\x12\x18\n" +
	"\amaximum\x18\a \x01(\tR\amaximum\x12\x18\n" +
	"\apattern\x18\b \x01(\tR\apattern\x12\x16\n" +
	"\x06format\x18\t \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"min_length\x18\n" +
	" \x01(\tR\tminLength\x12\x1d\n" +
	"\n" +
	"max_length\x18\v \x01(\tR\tmaxLengthBFZDgithub.com/aliyun/aliyun-openapi-runtime/source/format/pbmeta;pbmetab\x06proto3"

var (
	file_aliyun_openapi_meta_proto_rawDescOnce sync.Once
	file_aliyun_openapi_meta_proto_rawDescData []byte
)

func file_aliyun_openapi_meta_proto_rawDescGZIP() []byte {
	file_aliyun_openapi_meta_proto_rawDescOnce.Do(func() {
		file_aliyun_openapi_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aliyun_openapi_meta_proto_rawDesc), len(file_aliyun_openapi_meta_proto_rawDesc)))
	})
	return file_aliyun_openapi_meta_proto_rawDescData
}

var file_aliyun_openapi_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aliyun_openapi_meta_proto_goTypes = []any{
	(*CommandDefinition)(nil), // 0: aliyun.openapi.meta.v1.CommandDefinition
	(*Operation)(nil),         // 1: aliyun.openapi.meta.v1.Operation
	(*Argument)(nil),          // 2: aliyun.openapi.meta.v1.Argument
	(*TypeShape)(nil),         // 3: aliyun.openapi.meta.v1.TypeShape
}
var file_aliyun_openapi_meta_proto_depIdxs = []int32{
	1, // 0: aliyun.openapi.meta.v1.CommandDefinition.operation:type_name -> aliyun.openapi.meta.v1.Operation
	2, // 1: aliyun.openapi.meta.v1.CommandDefinition.parameters:type_name -> aliyun.openapi.meta.v1.Argument
	2, // 2: aliyun.openapi.meta.v1.Argument.fields:type_name -> aliyun.openapi.meta.v1.Argument
	3, // 3: aliyun.openapi.meta.v1.Argument.element:type_name -> aliyun.openapi.meta.v1.TypeShape
	3, // 4: aliyun.openapi.meta.v1.Argument.value:type_name -> aliyun.openapi.meta.v1.TypeShape
	2, // 5: aliyun.openapi.meta.v1.TypeShape.fields:type_name -> aliyun.openapi.meta.v1.Argument
	3, // 6: aliyun.openapi.meta.v1.TypeShape.element:type_name -> aliyun.openapi.meta.v1.TypeShape
	3, // 7: aliyun.openapi.meta.v1.TypeShape.value:type_name -> aliyun.openapi.meta.v1.TypeShape
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_aliyun_openapi_meta_proto_init() }
func file_aliyun_openapi_meta_proto_init() {
	if File_aliyun_openapi_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aliyun_openapi_meta_proto_rawDesc), len(file_aliyun_openapi_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aliyun_openapi_meta_proto_goTypes,
		DependencyIndexes: file_aliyun_openapi_meta_proto_depIdxs,
		MessageInfos:      file_aliyun_openapi_meta_proto_msgTypes,
	}.Build()
	File_aliyun_openapi_meta_proto = out.File
	file_aliyun_openapi_meta_proto_goTypes = nil
	file_aliyun_openapi_meta_proto_depIdxs = nil
}
