// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: logs.proto

package sls

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LogContent struct {
	Key                  *string  `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=Value" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogContent) Reset()         { *m = LogContent{} }
func (m *LogContent) String() string { return proto.CompactTextString(m) }
func (*LogContent) ProtoMessage()    {}
func (*LogContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_782e6d65c19305b4, []int{0}
}
func (m *LogContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogContent.Unmarshal(m, b)
}
func (m *LogContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogContent.Marshal(b, m, deterministic)
}
func (m *LogContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogContent.Merge(m, src)
}
func (m *LogContent) XXX_Size() int {
	return xxx_messageInfo_LogContent.Size(m)
}
func (m *LogContent) XXX_DiscardUnknown() {
	xxx_messageInfo_LogContent.DiscardUnknown(m)
}

var xxx_messageInfo_LogContent proto.InternalMessageInfo

func (m *LogContent) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *LogContent) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Log struct {
	Time                 *uint32       `protobuf:"varint,1,req,name=Time" json:"Time,omitempty"`
	Contents             []*LogContent `protobuf:"bytes,2,rep,name=Contents" json:"Contents,omitempty"`
	TimeNs               *uint32       `protobuf:"varint,4,opt,name=TimeNs" json:"TimeNs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_782e6d65c19305b4, []int{1}
}
func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Log) GetContents() []*LogContent {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *Log) GetTimeNs() uint32 {
	if m != nil && m.TimeNs != nil {
		return *m.TimeNs
	}
	return 0
}

type LogTag struct {
	Key                  *string  `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=Value" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogTag) Reset()         { *m = LogTag{} }
func (m *LogTag) String() string { return proto.CompactTextString(m) }
func (*LogTag) ProtoMessage()    {}
func (*LogTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_782e6d65c19305b4, []int{2}
}
func (m *LogTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogTag.Unmarshal(m, b)
}
func (m *LogTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogTag.Marshal(b, m, deterministic)
}
func (m *LogTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogTag.Merge(m, src)
}
func (m *LogTag) XXX_Size() int {
	return xxx_messageInfo_LogTag.Size(m)
}
func (m *LogTag) XXX_DiscardUnknown() {
	xxx_messageInfo_LogTag.DiscardUnknown(m)
}

var xxx_messageInfo_LogTag proto.InternalMessageInfo

func (m *LogTag) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *LogTag) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type LogGroup struct {
	Logs                 []*Log    `protobuf:"bytes,1,rep,name=Logs" json:"Logs,omitempty"`
	Topic                *string   `protobuf:"bytes,3,opt,name=Topic" json:"Topic,omitempty"`
	Source               *string   `protobuf:"bytes,4,opt,name=Source" json:"Source,omitempty"`
	LogTags              []*LogTag `protobuf:"bytes,6,rep,name=LogTags" json:"LogTags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LogGroup) Reset()         { *m = LogGroup{} }
func (m *LogGroup) String() string { return proto.CompactTextString(m) }
func (*LogGroup) ProtoMessage()    {}
func (*LogGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_782e6d65c19305b4, []int{3}
}
func (m *LogGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogGroup.Unmarshal(m, b)
}
func (m *LogGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogGroup.Marshal(b, m, deterministic)
}
func (m *LogGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogGroup.Merge(m, src)
}
func (m *LogGroup) XXX_Size() int {
	return xxx_messageInfo_LogGroup.Size(m)
}
func (m *LogGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_LogGroup.DiscardUnknown(m)
}

var xxx_messageInfo_LogGroup proto.InternalMessageInfo

func (m *LogGroup) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *LogGroup) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *LogGroup) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *LogGroup) GetLogTags() []*LogTag {
	if m != nil {
		return m.LogTags
	}
	return nil
}

type LogGroupList struct {
	LogGroups            []*LogGroup `protobuf:"bytes,1,rep,name=LogGroups" json:"LogGroups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LogGroupList) Reset()         { *m = LogGroupList{} }
func (m *LogGroupList) String() string { return proto.CompactTextString(m) }
func (*LogGroupList) ProtoMessage()    {}
func (*LogGroupList) Descriptor() ([]byte, []int) {
	return fileDescriptor_782e6d65c19305b4, []int{4}
}
func (m *LogGroupList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogGroupList.Unmarshal(m, b)
}
func (m *LogGroupList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogGroupList.Marshal(b, m, deterministic)
}
func (m *LogGroupList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogGroupList.Merge(m, src)
}
func (m *LogGroupList) XXX_Size() int {
	return xxx_messageInfo_LogGroupList.Size(m)
}
func (m *LogGroupList) XXX_DiscardUnknown() {
	xxx_messageInfo_LogGroupList.DiscardUnknown(m)
}

var xxx_messageInfo_LogGroupList proto.InternalMessageInfo

func (m *LogGroupList) GetLogGroups() []*LogGroup {
	if m != nil {
		return m.LogGroups
	}
	return nil
}

func init() {
	proto.RegisterType((*LogContent)(nil), "sls.LogContent")
	proto.RegisterType((*Log)(nil), "sls.Log")
	proto.RegisterType((*LogTag)(nil), "sls.LogTag")
	proto.RegisterType((*LogGroup)(nil), "sls.LogGroup")
	proto.RegisterType((*LogGroupList)(nil), "sls.LogGroupList")
}

func init() { proto.RegisterFile("logs.proto", fileDescriptor_782e6d65c19305b4) }

var fileDescriptor_782e6d65c19305b4 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8e, 0x3f, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0xc9, 0x9f, 0xcb, 0x25, 0x73, 0x06, 0x65, 0x10, 0xd9, 0xc2, 0x22, 0x04, 0x84, 0xc0,
	0x41, 0x10, 0xb1, 0xbb, 0x4e, 0x0b, 0x0b, 0x17, 0x8b, 0x35, 0x58, 0x58, 0x08, 0xe1, 0x08, 0x4b,
	0x60, 0xbd, 0x09, 0x99, 0xa4, 0xb0, 0xf0, 0xbb, 0xcb, 0xee, 0x65, 0xbd, 0xf6, 0xba, 0x79, 0x33,
	0xf3, 0xde, 0xfb, 0x01, 0x18, 0xd2, 0x5c, 0x0f, 0x23, 0x4d, 0x84, 0x11, 0x1b, 0x2e, 0x1f, 0x01,
	0x24, 0xe9, 0x67, 0x3a, 0x4c, 0xdd, 0x61, 0xc2, 0x2b, 0x88, 0x5e, 0xbb, 0x1f, 0x11, 0x14, 0x61,
	0x95, 0x29, 0x3b, 0xe2, 0x35, 0xac, 0x3e, 0x5a, 0x33, 0x77, 0x22, 0x74, 0xbb, 0xa3, 0x28, 0xbf,
	0x20, 0x92, 0xa4, 0x11, 0x21, 0x6e, 0xfa, 0xef, 0xce, 0xfd, 0xe7, 0xca, 0xcd, 0xb8, 0x85, 0x74,
	0x49, 0x63, 0x11, 0x16, 0x51, 0xb5, 0x79, 0xb8, 0xac, 0xd9, 0x70, 0x7d, 0x6a, 0x51, 0xff, 0x0f,
	0x78, 0x03, 0x89, 0x35, 0xbd, 0xb1, 0x88, 0x8b, 0xa0, 0xca, 0xd5, 0xa2, 0xca, 0x7b, 0x48, 0x24,
	0xe9, 0xa6, 0xd5, 0x67, 0x13, 0xfd, 0x42, 0x2a, 0x49, 0xbf, 0x8c, 0x34, 0x0f, 0x78, 0x0b, 0xb1,
	0x24, 0xcd, 0x22, 0x70, 0xf5, 0xa9, 0xaf, 0x57, 0x6e, 0x6b, 0xfd, 0x0d, 0x0d, 0xfd, 0x5e, 0x44,
	0x45, 0x60, 0xfd, 0x4e, 0x58, 0x92, 0x77, 0x9a, 0xc7, 0x7d, 0xe7, 0x48, 0x32, 0xb5, 0x28, 0xbc,
	0x83, 0xf5, 0x91, 0x84, 0x45, 0xe2, 0xe2, 0x36, 0x3e, 0xae, 0x69, 0xb5, 0xf2, 0xb7, 0x72, 0x07,
	0x17, 0xbe, 0x5e, 0xf6, 0x3c, 0xe1, 0x16, 0x32, 0xaf, 0x3d, 0x47, 0xee, 0x8d, 0x6e, 0xab, 0x4e,
	0xf7, 0xa7, 0xf5, 0xe7, 0xaa, 0xde, 0xb1, 0xe1, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x38, 0x55,
	0x39, 0x62, 0x9e, 0x01, 0x00, 0x00,
}
