#!/bin/bash

g_var=
g_error=0
force="force"

do_command() {
	if [[ $2 != $force && $g_error -eq 1 ]]
	then
		g_var=
		return $g_error
	fi

	cmd="$1 --access-key-id $ACCESS_KEY_ID --access-key-secret $ACCESS_KEY_SECRET --region cn-beijing 2>&1"

	echo "Command<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
	echo $cmd
	echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Command"

	g_var=$(eval $cmd)

	echo "Result<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
	echo $g_var
	echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Result"

	err=$(echo $g_var | grep -i "error")

	if [[ $2 != $force && $err != "" ]]
	then
		g_var=
		g_error=1
		return $g_error
	fi

	return 0
}